### ISSUE TITLE
block-loop.md file missing blog quote titles

### ISSUE THREAD

**Issue by JFernando122** [goldbergyoni/nodebestpractices#1001]
In `block-loop.md` there are 2 quotes but they don't have the structure

### Blog quote: title

little text about where this was taken from

>quote goes here

### Screenshot of the current view
![image](https://user-images.githubusercontent.com/40414805/120855042-92b8d700-c543-11eb-8a15-64b1ed39e41a.png)

**Comment by rluvaton** [comment]
Hey @JFernando122 thank you so much for opening this issue, could you please provide a path or which section the block-loop?
