### ISSUE TITLE
Promoting French translation

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#1015]
@forresst @tkhadir @MrYamous The French translation now appears under "Translations in progress" however it's done and it's a good time to promote it. Am I right? Is [this file ](https://github.com/goldbergyoni/nodebestpractices/blob/master/README.french.md) updated and I'm allowed to Tweet about and put in our news section?

p.s. If there are some French user groups (E.g., FaceBook), feel free to promote also there

**Comment by forresst** [comment]
By the PR #1018  I have just updated the French translation. 

The README is fully translated. There are still sections to be translated, you can follow the progress [here](https://github.com/forresst/nodebestpractices/issues/1)
