### ISSUE TITLE
Erro de digitação

### ISSUE THREAD

**Issue by Minozzzi** [goldbergyoni/nodebestpractices#1035]
No título do tópico 4.13 na versão português - BR, acredito que a a palavra isolatdamente deveria ser isoladamente

**Comment by pecampelo** [comment]
foi resolvido já, não sei pelo que

**Comment by rafaelconcept** [comment]
corrected in commit https://github.com/goldbergyoni/nodebestpractices/commit/a6f90d5f2cd263a8bcead7f657e16dd1a3801925
close the issue please
