### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by jahelo** [goldbergyoni/nodebestpractices#1069]
I would love to contribute/start a German translation. Is there already something going on in this direction?

**Comment by goldbergyoni** [comment]
@jahelo Welcome!

@BrunoScheufler You can probably chime-in and remind us what is the status for German translation?

**Comment by BrunoScheufler** [comment]
> @jahelo Welcome!
> 
> 
> 
> @BrunoScheufler You can probably chime-in and remind us what is the status for German translation?

Think we had started something a while ago but it's probably largely out of date now. Maybe it makes sense to start from scratch here

**Comment by jahelo** [comment]
as #939 seems to have not been decided on yet, how should i proceed? Just Fork and add a reader.german.md etc? or should we move #939 before adding more translations? 
what do you think @BrunoScheufler @goldbergyoni ?

**Comment by rluvaton** [comment]
I think you can just fork and add the `README.german.md` links, #939 might take a little time

**Comment by goldbergyoni** [comment]
@jahelo Here are some more instructions, does it makes things clear enough?


__


Having A German translation could be awesome! At the end, we can Tweet about this, put in our news section, include your name at the top of the translated language and also at the main home page contributors list.

Let's go for this? Few basic guideliness:

Work on your own fork - Fork this repo, create a branch for yourself, translate & collaborate with other translators, then finally when ready create a PR.

Focus on translation, not content editing - The focus is on translation, should you want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design).

Duplicate the readme and the inner pages - The content should be translated over a page duplication. readme.md became readme.{translated-language}.md (e.g. readme.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same. You may see examples in currently translated languages.

Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish).

We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, put homepage banner or anything else.

**Comment by jahelo** [comment]
ok, so i have started with the translation by creating a fork and creating all the *.german.md files. Also i've started translating the first paragraphs. So anyone who speaks german and is interested in helping -> Feel free to visit [](url)https://github.com/jahelo/nodebestpractices/blob/german-translation/README.german.md

**Comment by goldbergyoni** [comment]
@jahelo I'm putting this in the news section to grab attention of more people
