### ISSUE TITLE
Add a hint to nodejs-integration-test-best-practices in separateexpress.md

### ISSUE THREAD

**Issue by jahelo** [goldbergyoni/nodebestpractices#1074]
During the translations process i stumbled over the hint to separate the api and network configuration of express. The sentence "This allows testing the API in-process, without performing network calls, with all the benefits that it brings to the table: fast testing execution and getting coverage metrics of the code."

And although this does not seem wrong, i feel confused because in [nodejs-integration-tests-best-practices Section 3 Point 2](https://github.com/testjavascript/nodejs-integration-tests-best-practices#%EF%B8%8F-2-approach-the-api-using-a-library-that-is-a-pure-http-client-eg-axios-not-supertest) it is recommended to NOT use this approach.

I would say both texts are correct in their context, but we should add a hint to separeteexpress.md that there are other things that should be considered for testing and link to nodejs-integration-test-best-practices. 

What do you think?

**Comment by goldbergyoni** [comment]
@jahelo Somehow I missed this issue and only now noted 

You're absolutely right! Naturally, with time our opinions and techniques evolve, I changed my mind for all the good reasons that are explained in the integration tests best practice guide

We should definitely update this bullet here and maybe make it less Express-centric

If you're up for updating the bullet - Could be great. If not, I'll handle it
