### ISSUE TITLE
Formatting issue with 3.3

### ISSUE THREAD

**Issue by apainintheneck** [goldbergyoni/nodebestpractices#1116]
It looks like there is a formatting issue in section [3.3 Start a Codeblock's Curly Braces on the Same Line](https://github.com/goldbergyoni/nodebestpractices#-33-start-a-codeblocks-curly-braces-on-the-same-line).
![Screen Shot 2021-11-29 at 9 56 44 PM](https://user-images.githubusercontent.com/42982186/144001687-a4bed734-6962-44c2-a287-340b646a7efe.png)
As you can see the both do and avoid examples are identical.

It should be just a one line fix. Should I make a PR?

**Comment by elektronik2k5** [comment]
Yes, please. :)
