### ISSUE TITLE
Curly braces with the same position in brazilian translation code block

### ISSUE THREAD

**Issue by p-lacerda** [goldbergyoni/nodebestpractices#1142]
https://github.com/goldbergyoni/nodebestpractices/blob/b8bd67ec16734d60ac208b7309bde995abc097e5/README.brazilian-portuguese.md?plain=1#L267-L277

Hi, I noticed these curly braces are with the same position. It should be like this:

```
javascript
// Do
function someFunction() {
  // code block
}

// Avoid
function someFunction()
{
  // code block
}
```

**Comment by goldbergyoni** [comment]
@p-lacerda Great catch!

Would you mind PR-ing this small and important change?

**Comment by rluvaton** [comment]
Closing as fixed in https://github.com/goldbergyoni/nodebestpractices/commit/dcf152f6be7f077eb536f1e7f85d418e06cc57c2

Thanks!
