### ISSUE TITLE
Hebrew translation תירגום לעברית

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#156]
Call for Hebrew translator who are willing to contribute and translate the guide to Hebrew.

Branch was created here:
https://github.com/i0natan/nodebestpractices/blob/hebrew-translation/README.hebrew.md

cc @idori

**Comment by ereztaiar** [comment]
Hello i0natan,

I whold like to contribute to the translations of this repository.
Are there any limitations in time?

Thanks
Erez

**Comment by i0natan** [comment]
הי ארז,

נשמע מעולה. אשמח לשתף פעולה ולתרגם ביחד.

האם היית רוצה שנעשה את זה לאט לאורך שבועות או שנקבע איזה אחה"צ ובשעתיים נתרגם את כל עמוד הבית ביחד עם 

@idori

**Comment by ereztaiar** [comment]
הייי @i0natan ,

התחלתי לתרגם את עמוד הבית
https://github.com/ereztaiar/nodebestpractices/blob/hebrew-translation/README.hebrew.md
לדעתי עדיף לבצע את זה למשך כמה שבועות כי אני לא בטוח במידת הזמינות שלי
אעדכן אותך במידה ויתפנה לי זמן לסגור את התרגום ביום אחד

ארז

**Comment by i0natan** [comment]
@ereztaiar 

התירגום נראה מעולה. איך אתה מציע שנשתף פעולה: אולי לפי חלקים, למשל אני אתחיל עם החלק של טסטינג ואתה עם חלק אחר?

@ItayElgazar 
אשמח מאוד לשתף מחשבותיי בנושא, יש אפשרות שנפתח לזה כרטיס/אישו ייעודי שלא יתבלבל עם ההתכתבות לגבי התירגום? תוכל בכרטיס שאתה פותח לכתוב איפה מוגדרים הראוטים שלך?

**Comment by i0natan** [comment]
@ereztaiar @ItayElgazar Let's push this forward? one after-noon and it's done

**Comment by ormoyal** [comment]
היי לכם
זה יצא בסוף לפועל?

**Comment by i0natan** [comment]
> היי לכם
> זה יצא בסוף לפועל?

טרם

בא לך להשתתף?

@ereztaiar @ItayElgazar פינג למקרה שבא לכם אחה״צ משותף שבסופו סיימנו ונוכל לפרסם את זה גם בכתבת בלוג פוסט שלנו

**Comment by ItayElgazar** [comment]
יאללה. בואו נקבע שעה?
אני בשעון אמסטרדם, מסיים לעבוד בסביבות 5 (6 שלכם)

**Comment by ormoyal** [comment]
> > היי לכם
> > זה יצא בסוף לפועל?
> 
> טרם
> 
> בא לך להשתתף?
> 
> @ereztaiar @ItayElgazar פינג למקרה שבא לכם אחה״צ משותף שבסופו סיימנו ונוכל לפרסם את זה גם בכתבת בלוג פוסט שלנו

האמת שלא תיכננתי כי האנגלית שלי לא ברמה כל כך טובה, אבל אשמח לעזור במה שאפשר ומקסימום מישהו יעבור על זה לפני שיפורסם

**Comment by ItayElgazar** [comment]
לא, לא ענו :/
אפשר לקבוע למחר אם בא לכם, או יום ראשון או בכללי יום בשבוע הבא

**Comment by ItayElgazar** [comment]
@i0natan פינג

**Comment by i0natan** [comment]
> @i0natan פינג

אוי, איכשהו לא קפצה לי הודעה. סורי.

בטח, נוח לך השבוע ברביעי אחה״צ? אולי שבוע הבא בראשון?

**Comment by goldbergyoni** [comment]
Leaving this open just in case someone still wants to jump on this opprtunity

**Comment by ZivErlich** [comment]
היי @goldbergyoni 
אשמח לעזור בתרגום לעברית.
מבחינת זמינות, אעדיף לתרגם חלק חלק (אפשר לחלק בינינו מי מתרגם מה).

**Comment by Rhenzy1293** [comment]
Bisaya mode!

**Comment by goldbergyoni** [comment]
> היי @goldbergyoni
> אשמח לעזור בתרגום לעברית.
> מבחינת זמינות, אעדיף לתרגם חלק חלק (אפשר לחלק בינינו מי מתרגם מה)

נשמע על הכיפאק! עם איזה חלק בא לך להתחיל?

**Comment by yonatankarp** [comment]
גם אני יכול לעזור בתרגום :)
אני חושב שלפי חלקים יהיה הכי קל ויאפשר הכי הרבה גמישות

**Comment by goldbergyoni** [comment]
@yonatankarp 

נשמע טוב

**Comment by yonatankarp** [comment]
@goldbergyoni נראה שאין לי הרשאות לדחוף לבראץ' הקיים - סורי שלקח לי זמן להתחיל לעבוד על זה...

**Comment by goldbergyoni** [comment]
הכל טוב, בזמנך כמובן. 

אתה צריך לעשות פול ריקווסט. אם יותר נוח לך אתן לך הרשאות

מה מעדיף?

**Comment by yonatankarp** [comment]
לא באמת משנה לי,

אני מניח שפול ריקווסטים קטנים עדיפים על אחד ענק :)

**Comment by yonatankarp** [comment]
לצערי נראה שאני לא יכול גם לדחוף בראנץ חדש - אז אני אצטרך לקבל הרשאות בכל מקרה ואז אצור פול ריקווסט לבראנצ' המקורי

**Comment by nweiser1** [comment]
happy to help with translations if its still needed

**Comment by ilanbenyona-dev** [comment]
Let’s do it

**Comment by ShaiGilboa** [comment]
I'm also happy to help with the translation :)
אם בחרתם לעשות את זה בחלקים, ומתאים שאצטרף - אז רק תגידו איזה חלקים עוד יש לתרגם!

**Comment by omertalmi5** [comment]
פרויקט מבורך, אשמח שתגידו אם אוכל לעזור

**Comment by hodbauer** [comment]
@goldbergyoni 
גם אני אשמח לעזור.
איך אפשר להתניע פה את התהליך מחדש?

**Comment by goldbergyoni** [comment]
אהלן, יש רצון רב להניע שוב מחדש בימים הקרובים. האם אתם עדיין בעניין? איך הייתם מציעים לחלק את העבודה?

אני במקביל שואל תירגומים משפות אחרות שהצליחו יפה ובוצעו מספר משתמשים כיצד הם חילקו את העבודה

@hodbauer @ShaiGilboa @omertalmi5

**Comment by goldbergyoni** [comment]
@yuki_ota_ @desko27 Both of you did great in steering translation with multiple contributors, how did you sync and split the work? Contributor per section? Each forked and worked locally on his private fork? Other branching strategy? Thanks for sharing from your exprience

**Comment by omertalmi5** [comment]
@goldbergyoni 
אני אשמח
אוכל לעזור בחלק על docker

**Comment by YukiOta** [comment]
@goldbergyoni 

> how did you sync and split the work? Contributor per section? Each forked and worked locally on his private fork? Other branching strategy? Thanks for sharing from your exprience

We worked on only [the branch that I forked](https://github.com/YukiOta/nodebestpractices). When I forked it, I created `japanese-translation` branch and made it a default branch, and then each translator clone my forked repository and made PR on it. I've also created [a project board](https://github.com/YukiOta/nodebestpractices/projects/1) that includes tasks representing all sections to manage who would translate which section (all completed tasks are on the furthest right).

Hope it will help!

**Comment by michaelparkadze** [comment]
Is someone working on translating to Hebrew? would love to help translate as well or even start the process from scratch.

**Comment by hodbauer** [comment]
@michaelparkadze,
I was trying to start from scratch before a month (see former comment). But unfortunately I didn't do anything with it yet except of split it to issues.
So, or use my fork with issues, or if it easier for you,start from scratch and hopefully I will help you in something... 😬

**Comment by dvirsegev** [comment]
אני אשמח גם לקחת חלק בתרגום

**Comment by Yedidyar** [comment]
יש fork מעודכן או branch שאפשר להתחיל לעבוד עליו?
