### ISSUE TITLE
Add: Encryption of PII Data

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [goldbergyoni/nodebestpractices#316]
We need to add a note on encryption of Personally Identifiable Information (PII). PII data should be encrypted when stored

**Comment by i0natan** [comment]
Can you provide a few real-world examples + tools that help in achieving this(e.g. type of encryption)?

**Comment by VinayaSathyanarayana** [comment]
@goldbergyoni @js-kyle 

PII=personally identifiable information
Personally identifiable information (PII) is any data that can be used to identify a specific individual.

Data Privacy laws globally ask that the PII data is kept safe by encryption

Reference laws
European Union:  GDPR - https://ec.europa.eu/info/law/law-topic/data-protection_en
India: https://meity.gov.in/writereaddata/files/Personal_Data_Protection_Bill,2018.pdf
Singapore: https://www.pdpc.gov.sg/Legislation-and-Guidelines/Personal-Data-Protection-Act-Overview

**Comment by VinayaSathyanarayana** [comment]
Link to PII Data: https://en.wikipedia.org/wiki/Personal_data

**Comment by goldbergyoni** [comment]
@VinayaSathyanarayana Great to see you here again

This is an important design consideration, I would put it in the 'Common Node.js security best practices':
[Common Node.js security best practices](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/security/commonsecuritybestpractices.md)

Makes sense?

cc @js-kyle

**Comment by VinayaSathyanarayana** [comment]
Created Pull request #626

**Comment by josh-hemphill** [comment]
@VinayaSathyanarayana Does the merging of #626 close this?

**Comment by VinayaSathyanarayana** [comment]
Yes
