### ISSUE TITLE
Egyptian Arabic translation

### ISSUE THREAD

**Issue by nourkilany** [goldbergyoni/nodebestpractices#390]
I can help with the Egyptian Arabic translation.

**Comment by AbdelrahmanHafez** [comment]
I can help with that, even though I am not 100% sold on the idea because if you wanna be a good developer, you have to learn to read in English and utilize the English resources to stay truly up-to-date.

If the core maintainers decide that it's a good idea, and move forward with the idea, I'll be glad to help.

**Comment by nourkilany** [comment]
I agree 100%. but to those who are still learning English and struggling a bit, giving them the option to read this resource in Arabic and then alternate between the Arabic and English translation would be great in my honest opinion.

**Comment by i0natan** [comment]
@nourkilany - Welcome aboard 🎆 

@AbdelrahmanHafez Always great to see you re-visiting here! (p.s. did my testing advice helped?)

Having an Egyptian translation could be awesome

Let's go for this? Few basic guideliness:
1. Work on your own fork - fork, create a branch, translate & collaborate with other translators, then PR finally
2. Focus on translation, not content editing - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)
3. Duplicate the readme and the inner pages - the content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same
4. Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish)
5. We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, put homepage banner or anything else

**Comment by AbdelrahmanHafez** [comment]
Sounds great, @nourkilany would you like to take the lead on that? I am not available as much as I need to, but I'll make sure to contribute as much as my schedule allows me to.

@i0natan Always great to check things out around here, I've been away and couldn't try your approach in practice since I am serving my obligatory military service, you know how it is. Will keep you up to date ASAP. 😄

**Comment by nourkilany** [comment]
Okay sounds awesome. My pace is going to be kind of slow in the meantime, but I'll do my best.

**Comment by nourkilany** [comment]
I've been in a huge pile of work for the past 2 or so months

**Comment by goldbergyoni** [comment]
> I've been in a huge pile of work for the past 2 or so months

That's fine, we all here are pretty busy and sometimes do (Somehow) find the time. Take your time. Shall we leave this open and hope for some availability on your end or there is not even a chance and we better close?

**Comment by nourkilany** [comment]
let's leave it open and I'll try my best to find sometime to continue working on this

**Comment by AbdelrahmanHafez** [comment]
For me, I am 6 months away from finishing my military service, then I'll be more than happy to actively maintain an Egyptian Arabic translation.

It's a quite long duration, but it is what it is.

**Comment by oshliaer** [comment]
@nourkilany & @AbdelrahmanHafez 

You can try a challenge. For an example to push a practice per week. This repo contains specific branches for any language. Therefor you can just start.

If you're using vscode there is an extension [vscode-google-translate](https://marketplace.visualstudio.com/items?itemName=funkyremi.vscode-google-translate) by @funkyremi. For quick and thoughtful work I use line-by-line translation in markdown files.

**Comment by goldbergyoni** [comment]
> If you're using vscode there is an extension [vscode-google-translate](https://marketplace.visualstudio.com/items?itemName=funkyremi.vscode-google-translate) by @funkyremi. For quick and thoughtful work I use line-by-line translation in markdown files.

Amazing idea!

@nourkilany & @AbdelrahmanHafez We will be happy to see you whenever you find the time

**Comment by AbdelrahmanHafez** [comment]
I'll have much more free time in exactly 3 months, planning to start on it then.

**Comment by houssem-yahiaoui** [comment]
Hello @goldbergyoni , I would love to work on this one if the others are still busy and translate as much as I possibly can and why not finishing the whole repo, what's the status on it yet? do we have anything ? or I can fork it and start from scratch!

**Comment by goldbergyoni** [comment]
Hey @houssem-yahiaoui , great to have you here.

I would first ask @nourkilany @AbdelrahmanHafez about the progress?

**Comment by houssem-yahiaoui** [comment]
Hey Guys anything new on this one ? maybe nothing is done yet ? cc @goldbergyoni

**Comment by AbdelrahmanHafez** [comment]
@goldbergyoni 
My schedule is currently full of higher priority tasks, and I don't think I will have enough time to have a significant contribution to the translation in the foreseeable future.

@houssem-yahiaoui feel free to take the lead on this.

**Comment by houssem-yahiaoui** [comment]
@AbdelrahmanHafez wonderful, thanks for that  @goldbergyoni I think i will be in good shape to start this weekend, anything I should be aware of?

**Comment by houssem-yahiaoui** [comment]
@goldbergyoni can you please asign this to me as I'm working actively on it ? Thanks!

**Comment by goldbergyoni** [comment]
@AbdelrahmanHafez  Sure thing, appreciate your effort thus far!

@houssem-yahiaoui You are the lead! How can I help?

**Comment by houssem-yahiaoui** [comment]
@goldbergyoni Thanks! all good for now! I will ping you if any comes!

**Comment by goldbergyoni** [comment]
@houssem-yahiaoui Sounds great!
