### ISSUE TITLE
1.2 Layer your components, keep Express within its boundaries

### ISSUE THREAD

**Issue by bikingbadger** [goldbergyoni/nodebestpractices#393]
First I want to say a huge thank you for this resource. As someone just starting out it's great to see the community coming together to provide this. I'm was going over the list and on the layering components (1.2), I get the overall picture but when clicking on more details there is just a gif. Is there anyway to give a bit more detail on this page? I see that there is quite a nice detailed answer in #252 , I don't mind summarizing that into a pull request and giving the people who answered credits.

**Comment by bikingbadger** [comment]
I was a bit proactive and create a PR on what I was thinking.

**Comment by js-kyle** [comment]
@bikingbadger Thanks for the feedback + PR! We'll get that reviewed 👍

**Comment by delliriun** [comment]
A GIF/image is such a bad idea. How can blind people read this?
I lose one frame and need to  see everything again.

**Comment by malithrw** [comment]
I recently found this repo from a Reddit post and I have to say this has answered a lot of questions I had for sometime.

I agree with @delliriun on this. I experienced the same thing in `Layer your app, keep Express within its boundaries`'s 1min explainer GIF.

**Comment by i0natan** [comment]
@delliriun @malithrw A PR with better explanation is undergoing
