### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by stalniy** [goldbergyoni/nodebestpractices#395]
I can help with the Ukrainian translation -- progress will be slow(ish) though, so if anyone is willing to chip in, let me know.

- [ ] README @stalniy
  - [x] Project Structure
  - [x] Error handling
  - [x] Style guide
  - [x] Testing and quality
  - [ ] Going Produciton
  - [ ] Security
  - [ ] Performance
  - [ ] other details
- [ ] `.operations/writing-guidelines.md`
- [ ] Project Structure
- [ ] Error handling
- [ ] Style guide
- [ ] Testing and quality
- [ ] Going Produciton
- [ ] Security
- [ ] Performance
- [ ] Review and fix wording

**Comment by i0natan** [comment]
@BrunoScheufler See https://github.com/i0natan/nodebestpractices/blob/master/.operations/.common-answers.md

**Comment by stalniy** [comment]
@i0natan  Where do you get flag icons for translations?

**Comment by i0natan** [comment]
@stalniy Kudos, progress seems great 🎉 

@BrunoScheufler We split the work and each maintainer handles different languages, @BrunoScheufler will be glad to help here

p.s. Coming to Odessa, Kiev and Kharkhiv conferences in the next 3 months!

**Comment by stalniy** [comment]
@i0natan which conferences are you going to visit?

**Comment by i0natan** [comment]
I shall speak at odessaJS and KharkivJS + attend some conf at Kiev (no
details yet, customer asked me to attend).

Have plans to attend odessa or Kharkiv?

**Comment by stalniy** [comment]
just curious :) not sure yet whether I will attend

**Comment by stalniy** [comment]
In progress. Sorry didn’t have time recently to proceed

**Comment by goldbergyoni** [comment]
@stalniy It's 100% cool, take your time :)

Shall we maybe seek someone to help you?

**Comment by stalniy** [comment]
> @stalniy It's 100% cool, take your time :)
> 
> Shall we maybe seek someone to help you?

That would be great ! :) thanks

**Comment by goldbergyoni** [comment]
@BrunoScheufler Can you kindly handle this? we can Tweet, publish in Ukraine newsgroups, put under our news ('looking for...'), other ideas?

**Comment by BrunoScheufler** [comment]
Sure, we could also add this to our top README section as well, so if any users from Ukraine see it they can help out right away 👍

**Comment by stalniy** [comment]
still in progress

**Comment by goldbergyoni** [comment]
> still in progress

💚
