### ISSUE TITLE
Indonesian translation 

### ISSUE THREAD

**Issue by ikhsanalatsary** [goldbergyoni/nodebestpractices#400]
Great repo, helping people to learn best practice. It would be great if have indonesian translation to reach indonesian people native. I can help with the translation.

**Comment by i0natan** [comment]
@ikhsanalatsary  - Welcome aboard 🎆 

Having an Indonesian translation could be awesome

Let's go for this? Few basic guideliness:
1. Work on your own fork - fork, create a branch, translate & collaborate with other translators, then PR finally
2. Focus on translation, not content editing - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)
3. Duplicate the readme and the inner pages - the content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same
4. Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish)
5. We're here to help - let us know whether we can do anything to support you. We can Tweet about this work,

**Comment by js-kyle** [comment]
@ikhsanalatsary 👋 this was auto closed - should I reopen it/are you still actively working on this?
