### ISSUE TITLE
Possibly confusing error handling example

### ISSUE THREAD

**Issue by Calinou** [goldbergyoni/nodebestpractices#405]
First of all, thanks for writing this best practices list :slightly_smiling_face:

I've been going through this list as I'm working on an student project using Express.js. I'm trying to follow the best practices when it comes to error handling, but I'm a bit confused by one of the code samples given. In the [Distinguish operational vs programmer errors](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/operationalvsprogrammererror.md) best practice, it's recommended to not handle programmer errors specifically (other than gracefully restarting the application). However, in [Handle errors centrally. Not within middlewares](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/centralizedhandling.md), the following example seems to do the opposite:

https://github.com/i0natan/nodebestpractices/blob/7f60837666abc8e023d610b1350175d2b9fc5b08/sections/errorhandling/centralizedhandling.md#L28-L34

If I'm reading it correctly, it's redirecting the error to be handled by middleware (so that a message can be displayed to the user) *only* if it's a programmer error. This seems contradictory to the advice about handling operational errors specifically.

Am I understanding it correctly, or is it a typo in the example?

**Comment by i0natan** [comment]
@Calinou Welcome aboard 🍻 

There is an error there, but not related to the distinction between operational vs developer error: the error handler middleware should pass **any** error to the centralized handler as we want to unity the handling of **each** error.

Then, within the centralized handler, we act a bit differently based on the error type -> if it's !isOperational then we should also consider (maybe) to crash

Does this resonate with you?

**Comment by Calinou** [comment]
@i0natan Indeed, that sounds more logical to me :+1:

**Comment by i0natan** [comment]
@Calinou Great. If you want to contribute, you may adjust the example per our discussion. Or we can create an issue and wait for someone to take this. Whatever works for you

**Comment by Calinou** [comment]
@stale This issue is still relevant :slightly_smiling_face:

**Comment by Calinou** [comment]
This issue is still relevant :slightly_smiling_face:

**Comment by nicoqh** [comment]
I was also curious about this example, but the PR seem to have stalled.

The original concern was that only non-operational errors (i.e. programmer errors) will be passed down the middleware stack. I'm too new to Node to make any claims here, but shouldn't it be the other way around, like @Calinou suggested? The example doesn't seem to do what the "One Paragraph Explainer" says: "the middleware is being told whether this error is an untrusted error (not operational) so it can restart the app gracefully."

Shouldn't the example be something like this?

```javascript
// Error handling middleware, we delegate the handling to the centralized error handler
app.use(async (err, req, res, next) => {
  await errorHandler.handleError(err);

  if (isOperationalError) {
    // If this is a programmer error, pass it to the next middleware so it can
    // send an appropriate HTTP response with a user-friendly message.
    next(err);
  } else {
    // If this is a programmer error, here's an opportunity to crash the application
    process.exit(1);
  }
});
```

(Ignore the variable `isOperationalError` for a moment. In the original example, `handleError` doesn't return anything, so `isOperationalError` was undefined anyway.)

If so, can the centralized error handler also be in charge of crashing the application if it detects a programmer error from somewhere other than the middleware framework (Express)?

@webstacker seemed to think the current example is correct (it might well be!), so I'm tagging him as well.

Thoughts?

**Comment by nicoqh** [comment]
* I don't want to send 404 Not Found errors to an external reporting service
