### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by Andras-Simon** [goldbergyoni/nodebestpractices#407]
Hi! I would be happy to help with the Hungarian translation.

*EDIT* I included a task list so it is easier to follow where the translation is.
 - [ ] README
 - [x] Project Structure
 - [ ] Error handling
 - [X] Style Practices
 - [X] Testing and quality
 - [ ] Going Produciton
 - [ ] Security
 - [X] Performance

**Comment by BrunoScheufler** [comment]
@Andras-Simon - Awesome, welcome aboard 🎆

Having a Hungarian translation would be great 👍 

Before you start with this, we've prepared some basic workflow guidelines:

- Work on your own fork - fork, create a branch, translate & collaborate with other translators, then open a PR
- Focus on translation, not content editing - the focus is on translation, should anyone want to modify the content or the graphics - let's PR a draft in English first and then translate to other languages. Also the format of the text should remain intact (same design)
- Duplicate the readme and the inner pages - the content should be translated over at a duplicated page, step by step. As an example, README.md would be come README.{translated-language}.md (e.g. README.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same
- Collaborate - once you setup the translation foundation (branch, duplicate pages), we can announce the work on a new language and get others involved to support you in translating (if you wish so, of course)
We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, etc. 🚀

**Comment by Andras-Simon** [comment]
@BrunoScheufler - Thanks! I have just forked this repo and set up the hungarian-translation branch with the duplicates.

**Comment by i0natan** [comment]
@BrunoScheufler Just going over issues and ensuring they are all handles - is Hungarian assigned to you?

**Comment by BrunoScheufler** [comment]
@i0natan it doesn't look like we've added it to our operations manual at all so there's no assignee from what I can see currently 🤔 I could take it though 👍

**Comment by Andras-Simon** [comment]
Please keep it open for now, the last few months were busy, but I will try to find some time to finish the translation.

**Comment by goldbergyoni** [comment]
> Please keep it open for now, the last few months were busy, but I will try to find some time to finish the translation.

Sure thing! Take your time and hope to see you soon :)
