### ISSUE TITLE
Usage of https://allcontributors.org/

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#410]
Team @js-kyle @BrunoScheufler @sagirk ,

What do you think about https://allcontributors.org/?

**Comment by BrunoScheufler** [comment]
Sounds like a great idea to automate adding and keeping track of contributors 🚀 Let's add it!

**Comment by js-kyle** [comment]
Yeah! I think @sagirk suggested this one early on. I think it is good, and it would be great to have it automated

**Comment by i0natan** [comment]
Can one of you perform this?

I can only start in 3 weeks or so

**Comment by js-kyle** [comment]
@i0natan I don't think we can do it as it requires repo permissions to install the required Github app. I could take a look at it for sure, but just means you would need to give me higher access temporarily

**Comment by i0natan** [comment]
@js-kyle I'm willing to should give you any access you need, I just don't see that option. Please instruct

Anyway, I can just install the bot and you do the rest (if your calendar permits)

**Comment by js-kyle** [comment]
OK, perhaps you can add the bot to the repository, I have created a branch to start testing the configuration once the bot is ready

**Comment by i0natan** [comment]
> OK, perhaps you can add the bot to the repository,

Just did. Can you see it?

**Comment by js-kyle** [comment]
@all-contributors please add @js-kyle as a test

**Comment by js-kyle** [comment]
@all-contributors please add @js-kyle for code

**Comment by js-kyle** [comment]
@all-contributors-bot add @js-kyle

**Comment by js-kyle** [comment]
@all-contributors-bot add @js-kyle for code

**Comment by js-kyle** [comment]
@all-contributors please add @js-kyle for code

**Comment by js-kyle** [comment]
https://github.com/all-contributors/all-contributors-bot/issues/201

**Comment by js-kyle** [comment]
@all-contributors-bot please add @js-kyle for code

**Comment by i0natan** [comment]
@js-kyle  Maybe open an issue there? we are a big repo, they might help

**Comment by js-kyle** [comment]
@i0natan yep, it is related to this issue, so working with them on it at the moment https://github.com/all-contributors/all-contributors-bot/issues/201

**Comment by goldbergyoni** [comment]
@js-kyle Great, it seems they are responsive

**Comment by js-kyle** [comment]
@all-contributors-bot please add @js-kyle for code

**Comment by js-kyle** [comment]
OK great, this is working now! I'll take a look at some display/styling options now
