### ISSUE TITLE
July/August Maintenance

### ISSUE THREAD

**Issue by js-kyle** [goldbergyoni/nodebestpractices#447]
**Maintainer on call**: ??

**Updates**
- [ ] Update top badges with best practices item count, last update date and Node.js version
- [ ] Ensure all translations are aligned with the English version
- [ ] Update 'thank you' stars & flowers
- [ ] Notify and thank the contributors of the month
- [ ] Update news and updates
- [ ] Tweet it!

**Flowers**
- @lmammino
- @ziyaddin
- @namuwikilover

**Stars**
@theholidayinn

**News**
- Turkish translation

**Translation work**
Turkish @mperk

**Comment by lmammino** [comment]
No idea what is this 😅
Is this repo based on a rolling model for maintainers?

**Comment by js-kyle** [comment]
@lmammino Sorry! I did not make this one clear!

No - the reason you are mentioned here, is due to your latest contribution to the repository! Each month, we create an issue to track all new contributors to ensure we thank them for their efforts at the end of each month

So you don't need to worry about being a maintainer! But of course if you are keen to contribute more in the future that would be great!

**Comment by lmammino** [comment]
OK, thanks a lot for clarifying :)
