### ISSUE TITLE
What is the Russian translation status?

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#454]
Looks like there are a lot and amazing PR going on, is it 80% ready yet? If yes, I would 3rd on the flags list, Tweet, include in news, etc

@oshliaer @BrunoScheufler

**Comment by oshliaer** [comment]
@goldbergyoni 

As you can see the last PR is a Russian branch #453 

The branch is 100% translated and relevant.
I hope to do a proofreading already from the green branch.

**Comment by goldbergyoni** [comment]
@oshliaer Sounds amazing, I guess soon we wanna merge this to master

p.s. We selectively looking for new contributors and thus far enjoy collaborating with you. We plan some interesting projects which you can be involved with, do you want to hear more?

**Comment by oshliaer** [comment]
@goldbergyoni I'm open to any suggestions/offers/jobs/challenges/volunteering/coding/testing/translating etc.
I'd like to hear more.

**Comment by goldbergyoni** [comment]
@oshliaer Cool, where can we discuss in private: mail? twitter?

You may approach me: me@goldbergyoni.com

**Comment by contributorpw** [comment]
Hi!

What's a rule for merge a lang branch to the master?

**Comment by goldbergyoni** [comment]
@contributorpw That's awesome! Been waiting for this... :)

Ensure your local master is updated (pull latest), resolve conflicts if any (ping if need help), create a PR to our master. We will review shortly and merge. Then we would put a news announcement, add you to the contributor's list, tweet it and publish in few Node/js groups in Russia?

Make sure to put your name on the top of Russian language page, you well deserve it.

**Comment by contributorpw** [comment]
@slale All fine. Waiting a new PRs.
