### ISSUE TITLE
All contributors bot implementation

### ISSUE THREAD

**Issue by js-kyle** [goldbergyoni/nodebestpractices#459]
**NOTE:**
Why am I tagged in this issue?

If you have been tagged in this issue, it is due to us migrating our previous flowers/stars contribution model to using the all-contributors specification. This notification will only happen once.

---------------------

This issue tracks the remaining work items required for adding https://allcontributors.org/ spec and bot to this project.

- [x] create a CONTRIBUTORS.md file. This will be the new place where the main contributor table lives
- [x] update each language README.md to link to the new CONTRIBUTORS.md file
- [x] update our existing .operations/CONTRIBUTORS.md file to include instructions for how the new bot is used
- [x] remove existing flowers/stars, and use the bot to add contributors back in the new format.

Most of our existing flowers can be `content` or `translation` contributions, and stars are ideas https://allcontributors.org/docs/en/emoji-key.

As there is currently no way to bulk add contributors, there will be a process of many PR's to get this working initially, i.e. `@bot please add 1 for x, @bot please add 2 for x`.

This will be great for our workflow, which has become a bit difficult to manage~

**Comment by js-kyle** [comment]
Commands to replace current stars flowers list after merge:

```
@all-contributors-bot please add @kevinrambaud
@all-contributors-bot please add @mfine15
@all-contributors-bot please add @squgeim
@all-contributors-bot please add @matheusrocha89
@all-contributors-bot please add @BitYog
@all-contributors-bot please add @kudapara
@all-contributors-bot please add @t1st3
@all-contributors-bot please add @mulijordan1976
@all-contributors-bot please add @matchai
@all-contributors-bot please add @fabiothiroki
@all-contributors-bot please add @jsumners
@all-contributors-bot please add @crowchirp
@all-contributors-bot please add @dan-gamble
@all-contributors-bot please add @trainorpj
@all-contributors-bot please add @reod
@all-contributors-bot please add @yonjah
@all-contributors-bot please add @hazolsky
@all-contributors-bot please add @EvgenyOrekhov
@all-contributors-bot please add @gediminasml
@all-contributors-bot please add @hisaac
@all-contributors-bot please add @vkaracic
@all-contributors-bot please add @lallenlowe
@all-contributors-bot please add @nwwells
@all-contributors-bot please add @paulovitin
@all-contributors-bot please add @syzer
@all-contributors-bot please add @davesnx
@all-contributors-bot please add @pupix
@all-contributors-bot please add @spaxe
@all-contributors-bot please add @ocularrhythm
@all-contributors-bot please add @septa97
@all-contributors-bot please add @AllenFang
@all-contributors-bot please add @leonardovillela
@all-contributors-bot please add @MichalZalecki
@all-contributors-bot please add @chrisnicola
@all-contributors-bot please add @aecorredor
@all-contributors-bot please add @ymhtut
@all-contributors-bot please add @cwar
@all-contributors-bot please add @keyfoxth
@all-contributors-bot please add @utkarshbhatt12
@all-contributors-bot please add @duartemendes
@all-contributors-bot please add @serv
@all-contributors-bot please add @Max101
@all-contributors-bot please add @SandroMiguel
@all-contributors-bot please add @GabeKuslansky
@all-contributors-bot please add @ripper234
@all-contributors-bot please add @vkarpov15
@all-contributors-bot please add @imsergiobernal
@all-contributors-bot please add @ntelkedzhiev
@all-contributors-bot please add @vitordagamagodoy
@all-contributors-bot please add @manishsaraan
@all-contributors-bot please add @uronly14me
@all-contributors-bot please add @blackmatch
@all-contributors-bot please add @ISNIT0
@all-contributors-bot please add @BusbyActual
@all-contributors-bot please add @ImanMh
@all-contributors-bot please add @HeeL
@all-contributors-bot please add @kapilepatel
@all-contributors-bot please add @justjavac
@all-contributors-bot please add @hozefaj
@all-contributors-bot please add @el-ethan
@all-contributors-bot please add @milkdeliver
@all-contributors-bot please add @ArlindXh
@all-contributors-bot please add @ttous
@all-contributors-bot please add @LewisArdern
@all-contributors-bot please add @GabrielLidenor
@all-contributors-bot please add @animir
@all-contributors-bot please add @Francozeira
@all-contributors-bot please add @Invvard
@all-contributors-bot please add @romulogarofalo
@all-contributors-bot please add @thoqbk
@all-contributors-bot please add @Qeneke
@all-contributors-bot please add @MartinMuzatko
@all-contributors-bot please add @autoboxer
@all-contributors-bot please add @bikingbadger
@all-contributors-bot please add @ChangJoo-Park
@all-contributors-bot please add @MasahiroSakaguchi
@all-contributors-bot please add @TheHollidayInn
@all-contributors-bot please add @coreyc
@all-contributors-bot please add @Berkmann18
@all-contributors-bot please add @DouglasMV
@all-contributors-bot please add @marcelosdm
@all-contributors-bot please add @mperk
@all-contributors-bot please add @ryanouyang
```

**Comment by js-kyle** [comment]
This is ready for review. The process will be

- merge connected PR
- run through the above commands, then merge PRs as I go

After that initial setup, it will be as easy as using the bot for new contributions - no monthly tasks 😄

**Comment by js-kyle** [comment]
@goldbergyoni Are you happy for me to go ahead with the above? Everything is ready to go - there will just be alot of PR's on the repo when I use the bot to run the above commands (I will take care of them)

**Comment by js-kyle** [comment]
Going ahead with this - apologies for the incoming spam 😂

**Comment by js-kyle** [comment]
@all-contributors-bot please add @kevinrambaud

**Comment by js-kyle** [comment]
@all-contributors-bot please add @kevinrambaud for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @mfine15 for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @squgeim  for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @matheusrocha89  for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @BitYog  for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @kudapara  for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @t1st3  for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @mulijordan1976  for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @matchai  for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @fabiothiroki  for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @jsumners  for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @crowchirp  for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @dan-gamble for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @trainorpj for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @reod for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @yonjah for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @hazolsky for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @EvgenyOrekhov for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @gediminasml for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @hisaac for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @vkaracic for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @lallenlowe for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @nwwells for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @paulovitin for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @syzer for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @davesnx for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @pupix for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @spaxe for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @ocularrhythm for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @septa97 for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @AllenFang for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @leonardovillela for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @MichalZalecki for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @chrisnicola for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @aecorredor for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @ymhtut for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @cwar for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @keyfoxth for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @utkarshbhatt12 for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @duartemendes for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @serv for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @Max101 for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @SandroMiguel for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @GabeKuslansky for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @ripper234 for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @vkarpov15 for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @imsergiobernal for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @ntelkedzhiev for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @vitordagamagodoy for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @manishsaraan for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @uronly14me for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @blackmatch for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @ISNIT0 for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @BusbyActual for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @ImanMh for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @HeeL for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @kapilepatel for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @justjavac for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @hozefaj for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @el-ethan for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @milkdeliver for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @ArlindXh for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @ttous for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @LewisArdern for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @GabrielLidenor for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @animir for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @Francozeira for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @Invvard for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @romulogarofalo for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @thoqbk for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @Qeneke for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @MartinMuzatko for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @autoboxer for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @bikingbadger for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @ChangJoo-Park for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @MasahiroSakaguchi for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @TheHollidayInn for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @coreyc for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @Berkmann18 for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @DouglasMV for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @marcelosdm for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @mperk for content

**Comment by js-kyle** [comment]
@all-contributors-bot please add @ryanouyang for content

**Comment by bdresser** [comment]
Hi @js-kyle! I'm a product manager at GitHub. We're exploring ways to improve the process of recognizing & appreciating community members. Would you be down to chat briefly about your experience? Feel free to email me at bdresser@github.com if you're interested. 

Thanks for the work you're doing!
