### ISSUE TITLE
Clarify the explanation on how to create layers

### ISSUE THREAD

**Issue by andersonaguiar** [goldbergyoni/nodebestpractices#460]
In this page: https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/projectstructre/createlayers.md

I can see two possible improvements:

- Exemplify using res returns as well, in this page it's showing only how to deal with req but not with res
- You should change that .gif image, gifs don't allow you to have control over it (stop/play/rewind/forward), prefer text instead or video.

**Comment by js-kyle** [comment]
Agree on the comment about the .gif - we should aim to be as accessible as possible 👍

**Comment by goldbergyoni** [comment]
@andersonaguiar Welcome aboard ✋ 

You're 100% right, see #394  it's on our todo but there are so many other things. This will happen in the next 2-3 months. If you want to help in writing this - please let us know

**Comment by andersonaguiar** [comment]
Great, really good to know that you guys already have considered this change. Sure thing, I'm just a finishing a side project, once it's done I can jump into it to help you guys with the changes.
