### ISSUE TITLE
Example express app which encompasses all of the advice

### ISSUE THREAD

**Issue by noway** [goldbergyoni/nodebestpractices#464]
It would be really great to have an example app which illustrates all of the advice in the repo. I.e. an app written by all the best practices.

Something simple, like TODOMVC should be suffice.

Cheers.

**Comment by BrunoScheufler** [comment]
Hey there! We've had this idea come up several times, for example in #435 #430 👍 I think it might help to source all of this in one issue and go forward with this. Any thoughts and things I've missed on this @goldbergyoni?

**Comment by noway** [comment]
Sweet, I'll close the issue in that case in order not to clutter the issue list :-)

**Comment by BrunoScheufler** [comment]
@noway thanks 🙌  And thank you for bringing this up, even if this was posted before, that's not a problem at all, as it helps us to measure the demand for these projects 🚀
