### ISSUE TITLE
Spellcheck CI

### ISSUE THREAD

**Issue by js-kyle** [goldbergyoni/nodebestpractices#550]
I'm keen to start a small project of running some sort of spell check on CI, at least for our English files initially. It's very easy to make spelling mistakes when editing markdown, (for me at least), as well as hard to spot reviewing

**Comment by js-kyle** [comment]
Potentially something like this, there are likely more popular options https://www.npmjs.com/package/markdown-spellcheck

**Comment by js-kyle** [comment]
This is a sample of what it looks like on the README file at the moment. We might have too much technical jargon that it could be more annoying to have to add exclusions all the time

![image](https://user-images.githubusercontent.com/23022619/63493928-c2365500-c510-11e9-85c9-9ceff0f775eb.png)

**Comment by js-kyle** [comment]
Probably more hassle that it is worth I think. The tool works well, but we would need to heavily maintain an exclusion list

**Comment by goldbergyoni** [comment]
@js-kyle Like the approach, we should keep on and embrace automated quality tools!
