### ISSUE TITLE
Reconsider on suggesting bunyan as a logger

### ISSUE THREAD

**Issue by halfzebra** [goldbergyoni/nodebestpractices#556]
In a section about [logging](https://github.com/goldbergyoni/nodebestpractices#-27-use-a-mature-logger-to-increase-error-visibility) it is suggested to use Bunyan as a logging library.

The project is not currently active https://github.com/trentm/node-bunyan/issues/586 and it's probably not the best suggestion for people seeking guidance.

I propose to remove it as a suggested library until the repo has an active maintainer.

What do you think?

**Comment by oshliaer** [comment]
Bunyan is mentioned already https://github.com/goldbergyoni/nodebestpractices#-27-use-a-mature-logger-to-increase-error-visibility

**Comment by oshliaer** [comment]
This correlate with [writing-guidelines part 6 leading vendors only](https://github.com/goldbergyoni/nodebestpractices/blob/master/.operations/writing-guidelines.md#6-leading-vendors-only)

**Comment by goldbergyoni** [comment]
@halfzebra Yes, good catch 🙏

**Comment by dcsan** [comment]
what do you recommend instead?

**Comment by halfzebra** [comment]
I like using Pino and I would recommend it to anyone doing Node.js servers.
