### ISSUE TITLE
Typescript best practices

### ISSUE THREAD

**Issue by jfgabriel** [goldbergyoni/nodebestpractices#564]
Hello guys, is someone working on Typescript best practices? If not, should we start 😄 ?

**Comment by goldbergyoni** [comment]
@jfgabriel Welcome aboard, interesting idea, can you make it more tangible with few examples for good TS practices?

**Comment by gogoyqj** [comment]
use nestjs!

**Comment by goldbergyoni** [comment]
> use nestjs!

That might be a good idea for some teams and some projects, how do you find your work with it so far? what did you like/dislike?
