### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by P1X3L0V4** [goldbergyoni/nodebestpractices#574]
This issue thread is dedicated to add Polish translation to [goldbergyoni/nodebestpractices](https://github.com/goldbergyoni/nodebestpractices)

**Fork:** [P1X3L0V4/nodebestpractices](https://github.com/P1X3L0V4/nodebestpractices)

**Branch:** _pl_

## Status

_Updated as of October 24, 2019_

### Initial

- [X] Initial Polish Translation (Fork)
- [ ] README.polish (/README.polish.md)

### Code Style Practices

- [ ] Using ESLint and Prettier (codestylepractices/eslint_prettier.polish.md)

### Error Handling

- [ ] apmproducts.polish.md
- [ ] asyncerrorhandling.polish.md
- [ ] catchunhandledpromiserejection.polish.md
- [ ] centralizedhandling.polish.md
- [ ] documentingusingswagger.polish.md
- [ ] failfast.polish.md
- [ ] monitoring.polish.md
- [ ] operationalvsprogrammererror.polish.md
- [ ] shuttingtheprocess.polish.md
- [ ] testingerrorflows.polish.md
- [ ] usematurelogger.polish.md
- [ ] useonlythebuiltinerror.polish.md

### Performance

- [ ] block-loop.polish.md
- [ ] nativeoverutil.polish.md

### Production

- [ ] apmproducts.polish.md
- [ ] assigntransactionid.polish.md
- [ ] bestateless.polish.md
- [ ] createmaintenanceendpoint.polish.md
- [ ] delegatetoproxy.polish.md
- [ ] detectvulnerabilities.polish.md
- [ ] frontendout.polish.md
- [ ] guardprocess.polish.md
- [ ] lockdependencies.polish.md
- [ ] logrouting.polish.md
- [ ] LTSrelease.polish.md
- [ ] measurememory.polish.md
- [ ] monitoring.polish.md
- [ ] productioncode.polish.md
- [ ] setnodeenv.polish.md
- [ ] smartlogging.polish.md
- [ ] utilizecpu.polish.md

### Project Structure

- [ ] breakintcomponents.polish.md
- [ ] configguide.polish.md
- [ ] createlayers.polish.md
- [ ] separateexpress.polish.md
- [ ] thincomponents.polish.md
- [ ] wraputilities.polish.md

### Security

- [ ] avoid_publishing_secrets.polish.md
- [ ] avoideval.polish.md
- [ ] bcryptpasswords.polish.md
- [ ] childprocesses.polish.md
- [ ] commonsecuritybestpractices.polish.md
- [ ] dependencysecurity.polish.md
- [ ] escape-output.polish.md
- [ ] expirejwt.polish.md
- [ ] hideerrors.polish.md
- [ ] limitrequests.polish.md
- [ ] lintrules.polish.md
- [ ] login-rate-limit.polish.md
- [ ] non-root-user.polish.md
- [ ] ormodmusage.polish.md
- [ ] regex.polish.md
- [ ] requestpayloadsizelimit.polish.md
- [ ] safemoduleloading.polish.md
- [ ] saferedirects.polish.md
- [ ] sandbox.polish.md
- [ ] secretmanagement.polish.md
- [ ] secureheaders.polish.md
- [ ] secureserver.polish.md
- [ ] sessions.polish.md
- [ ] validation.polish.md

### Testing and quality

- [ ] 3-parts-in-name.polish.md
- [ ] aaa.polish.md
- [ ] avoid-global-test-fixture.polish.md
- [ ] bumpversion.polish.md
- [ ] citools.polish.md
- [ ] refactoring.polish.md

**Comment by goldbergyoni** [comment]
@P1X3L0V4  - Welcome aboard 🎆

Having a Polish translation could be awesome

Let's go for this? Few basic guideliness:
1. Work on your own fork - fork, create a branch, translate & collaborate with other translators, then PR finally
2. Focus on translation, not content editing - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)
3. Duplicate the readme and the inner pages - the content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same
4. Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish)
5. We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, put homepage banner or anything else

🙏 👍
