### ISSUE TITLE
TypeScript examples

### ISSUE THREAD

**Issue by kevynb** [goldbergyoni/nodebestpractices#579]
Hello,

I saw in the Readme that you're looking for Typescript examples. I think I'm up to the task.

What do you need? Is it just another code block under existing examples using Typescript types?

**Comment by goldbergyoni** [comment]
@kevynb Welcome and sorry for the late reply, I was traveling recently and only now found some free time

Yes, your proposal sounds great. I would create one example, to see how the format looks like, and then discuss this with the team here @BrunoScheufler and @js-kyle and once we love the format we can go to the distance

Just an idea - we can maybe use HTML detail tag to place two examples (JS & TS), so the user will see a title with the code explanation (e.g. throwing an error properly) and then expand it to see JS & TS examples

**Comment by goldbergyoni** [comment]
### Code example: deciding whether to crash

<details><summary><b>JavaScript</b></summary>

```javascript
// Assuming developers mark known operational errors with error.isOperational=true, read best practice #3
process.on('uncaughtException', function(error) {
  errorManagement.handler.handleError(error);
  if(!errorManagement.handler.isTrustedError(error))
  process.exit(1)
});

// centralized error handler encapsulates error-handling related logic
function errorHandler() {
  this.handleError = function (error) {
    return logger.logError(err)
      .then(sendMailToAdminIfCritical)
      .then(saveInOpsQueueIfCritical)
      .then(determineIfOperationalError);
  }

  this.isTrustedError = function (error) {
    return error.isOperational;
  }
}
```
</details>

<br/>
<details><summary><b>TypeScript</b></summary>

```javascript
// Assuming developers mark known operational errors with error.isOperational=true, read best practice #3
process.on('uncaughtException', function(error) {
  errorManagement.handler.handleError(error);
  if(!errorManagement.handler.isTrustedError(error))
  process.exit(1)
});

// centralized error handler encapsulates error-handling related logic
function errorHandler() {
  this.handleError = function (error) {
    return logger.logError(err)
      .then(sendMailToAdminIfCritical)
      .then(saveInOpsQueueIfCritical)
      .then(determineIfOperationalError);
  }

  this.isTrustedError = function (error) {
    return error.isOperational;
  }
}
```
</details>

**Comment by kevynb** [comment]
Yeah, that looks good to me! 
I'll start converting some code while we wait for confirmation from the others.
