### ISSUE TITLE
Structuring project by components - any real examples?

### ISSUE THREAD

**Issue by erezhod** [goldbergyoni/nodebestpractices#596]
Hi @goldbergyoni!
First of all, let me say thank you for sharing this amazing knowledge base, helps a lot.

I'm trying to re-structure a project that I'm currently working on for a client (Enterprise one) and it's a RESTful API using Node+Express which is currently structured the "classic" way (models, controllers, routes, etc...).

I tried following what you and the contributors mention [here](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.md) but I cannot seem to actually understand how to isolate components that far - kinda lacks more examples.

Are there any live code examples that demonstrate this methodology?

Thanks a lot! 🙂

**Comment by syffs** [comment]
It would make sense to have a full sample (or even a starter) project or even implementing most of the guidlines described here.

**Comment by goldbergyoni** [comment]
> Are there any live code examples that demonstrate this methodology?

@erezhod I don't have something self-explanatory but should I hold a (free obviously) webinar in December will you join?

@syffs Yeah, you're right. Just don't have the time... Have many parts of these practices spreaded around customers projects but need few days to assemble all of them together

**Comment by erezhod** [comment]
> @erezhod I don't have something self-explanatory but should I hold a (free obviously) webinar in December will you join?

Of course!

**Comment by syffs** [comment]
> It would make sense to have a full sample (or even a starter) project implementing most of the guidlines described here.

In the same spirit, there's [this repo](https://github.com/santiq/bulletproof-nodejs/), but it apparently does not implement all the best practices mentioned here. 

For instance, the app is well layered, but by technical roles, not by components.

**Comment by Stayfi** [comment]
If you can check my sample and give me any feedback

Didn't implement everything but what it's needed to a simple server bootstrap

https://github.com/Stayfi/nodejs-server

**Comment by MickaelNeves** [comment]
There's a very basic starting point [here](https://www.youtube.com/watch?v=NAd7TjfTk2I) I guess.

**Comment by syffs** [comment]
> There's a very basic starting point [here](https://www.youtube.com/watch?v=NAd7TjfTk2I) I guess.

@MickaelNeves this is only my opinion, but I don't think this is an example anyone looking for best practices should follow:
- it is way too basic to provide enough material for structuring an app
- it's not well layered or structured: business logic is arranged in a very questionable way in api/resource folder

@goldbergyoni imo, all these different approaches and interpretations well demonstrate the need for a full featured sample. My feeling is that [this repo](https://github.com/santiq/bulletproof-nodejs/) is an educated starting point that would be decent relayered by component with a few tweaks. 
Any thoughts ?

**Comment by MickaelNeves** [comment]
@syffs ok, so...

based on Uncle Bob's Clean Architecture, [here's](https://github.com/jbuget/nodejs-clean-architecture-app) an example of NodeJS and [here's](https://www.youtube.com/watch?v=CnailTcJV_U) an example with NodeJS + Mongo + Express.

**Comment by Stayfi** [comment]
Hi,

I want to share my repository, if you could have a check abd give me feedback about my "Uncle Bob" clean architecture implementation.

This schema show how i implemented it.

![uncle_bob_implementation](https://user-images.githubusercontent.com/6870442/76532496-f9e9f780-6476-11ea-99e3-066bd44c5aa8.png)

**Comment by syffs** [comment]
@Stayfi once again this is only my opinion... I think that this "architecture" introduces way too much complexity for the value its adds. 

**I'd say keep it simple !**

If you pay attention, that's one of the main purpose of the architecture best practices described in this repo... For instance, why [layering your app](https://github.com/goldbergyoni/nodebestpractices#-12-layer-your-components-keep-express-within-its-boundaries) ? Simply because it breaks your app into simpler and smaller pieces easier to understand. Luckily, it also separates concerns which will also greatly improve your dev scalability.

**Comment by torongu** [comment]
Hi, 
In this structure example, it's okay if I use the `userService` inside the `productController`

![image](https://user-images.githubusercontent.com/39832761/81204589-994ce600-8ff3-11ea-947b-aed9a9f21056.png)

**Comment by syong9295** [comment]
examples still needed
