### ISSUE TITLE
Where else would the centralized error handler be used other than middleware?

### ISSUE THREAD

**Issue by webstacker** [goldbergyoni/nodebestpractices#597]
https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/errorhandling/centralizedhandling.md

I'm obviously missing something here...

> Note that it’s a common, yet wrong, practice to handle errors within Express middleware – doing so will not cover errors that are thrown in non-web interfaces.

What is an example of this?

> Code Example – Anti Pattern: handling errors within the middleware
> // middleware handling the error directly, who will handle Cron jobs and testing errors?

How would the centralized error handler be used with Cron jobs and testing errors?

**Comment by goldbergyoni** [comment]
Sorry for missing this question, somehow noticed only now.

I'm putting testing aside and exemplify with CRON + Serverless: a centralized handler is a plain JS object that handles error for any type of application. It can emit metric error, log, etc

Does this make sense?
