### ISSUE TITLE
This sentence in 2.9 is missing something, not sure what

### ISSUE THREAD

**Issue by taylankasap** [goldbergyoni/nodebestpractices#601]
At the beginning of [2.9 Discover errors and downtime using APM products](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/errorhandling/apmproducts.md) it says:

> Traditional error handling assumes the existence of Exception **[[feels like this part is missing something]]** but application errors might come in the form of slow code paths, API downtime, lack of computational resources and more.

Maybe it meant something like this?

> Traditional error handling assumes the existence of **e**xception **as a code related problem** but application errors might come in the form of slow code paths, API downtime, lack of computational resources and more.

**Comment by goldbergyoni** [comment]
Yes! Much better wording, could you PR? 🎉
