### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by MIKOLAJW197** [goldbergyoni/nodebestpractices#603]
Have you thought about adding a Polish translation?
In the near future I could take care of that 🚀

**Comment by js-kyle** [comment]
Hey @MIKOLAJW197 a start has been made on Polish! You can take a look at progress here, and help out if you would like to! https://github.com/goldbergyoni/nodebestpractices/issues/574

**Comment by goldbergyoni** [comment]
@MIKOLAJW197 Could be awesome to have Polish translation!

**Comment by goldbergyoni** [comment]
@MIKOLAJW197 Including here some further instructions 🎆

Having a Polish translation could be awesome

Let's go for this? Few basic guideliness:

Work on your own fork - fork, create a branch, translate & collaborate with other translators, then PR finally
Focus on translation, not content editing - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)
Duplicate the readme and the inner pages - the content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same
Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish)
We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, put homepage banner or anything else
