### ISSUE TITLE
Framework suggestion like express.js, hapi.js, koa.js etc.

### ISSUE THREAD

**Issue by skt1598** [goldbergyoni/nodebestpractices#608]
Please add suggestions for frameworks also. As it's the very basic and most important thing for project. 
For example frameworks like hapi.js, express.js, koa.js, loopback etc.

**Comment by goldbergyoni** [comment]
@skt1598 Welcome. I'm not sure we should do this as this changes frequently and not really related to best practices. What @BrunoScheufler and @js-kyle think?

**Comment by BrunoScheufler** [comment]
@goldbergyoni this sounds like an opportunity for a side project we can refer to in the best practices since you're completely right, those libraries change more or less frequently but can be decoupled from bare Node.js

**Comment by skt1598** [comment]
> @goldbergyoni this sounds like an opportunity for a side project we can refer to in the best practices since you're completely right, those libraries change more or less frequently but can be decoupled from bare Node.js

**Comment by skt1598** [comment]
@goldbergyoni @BrunoScheufler @js-kyle I know that framework changes with time but this repo is a great source to learn how to build a good nodejs project and to get help in choosing various things for projects. And the framework is a very important part of any project. So I think it should be there whether as a separate project or in this repo only. But if you'll start a new project it'll take a lot more time to grow. So I think adding in this project will be a better option.

**Comment by goldbergyoni** [comment]
@skt1598 The need is there, I clearly see the value. I'll try to kick this off some time, we have 1-2 other initiatives that I'd like to explore first

**Comment by skt1598** [comment]
@goldbergyoni Thankyou. Please let me know if you start this project anytime.
