### ISSUE TITLE
[Conflict] Use only the built-in Error object

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [goldbergyoni/nodebestpractices#609]
In bullet _2.2 Use only the built-in Error object_ [Read More](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/errorhandling/useonlythebuiltinerror.md) the [code example](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/errorhandling/useonlythebuiltinerror.md#code-example--doing-it-even-better), _doing it even better_, we're defining an `AppError(...)` which extends the default `Error(...)` constructor.

However, in the quoted articles below, they seem to disagree that this is the right approach to things. Especially the [quote](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/errorhandling/useonlythebuiltinerror.md#blog-quote-inheriting-from-error-doesnt-add-too-much-value) from "Inheriting from Error doesn’t add too much value".

Am I misunderstanding the quote? Or are we trying to show different opinions on the matter?

**Comment by goldbergyoni** [comment]
It's not clear enough indeed.

Good practice - extend the Error object ONCE for all of the application exceptions. That is to say, create one and only one 'AppError'

Doubtful practice - extend the Error object for EACH application error like HttpError, DbError

Is the difference clear?

**Comment by AbdelrahmanHafez** [comment]
The difference is clear to me now, thank you!

I put in a PR that makes the difference a little bit more clear.
