### ISSUE TITLE
Catch unhandled promise rejections best practice

### ISSUE THREAD

**Issue by sadokmtir** [goldbergyoni/nodebestpractices#617]
I think it is worth mentioning that the solution stated **Catching unresolved and rejected promises** is not always valid. what I mean is that if a promise is caught on a later turn of the Node.js event loop, then probably throwing an error on this global catch is not a good idea. I am wondering how this is counted as **best practice** while obviously from the node official documentation it should not.

> There is no notion of a top level for a Promise chain at which rejections can always be handled. Being inherently asynchronous in nature, a Promise rejection can be handled at a future point in time — possibly much later than the event loop turn it takes for the '**unhandledRejection**' event to be emitted.

also:
> In asynchronous code, the 'unhandledRejection' event is emitted when the list of unhandled rejections grows, and the 'rejectionHandled' event is emitted when the list of unhandled rejections shrinks.

IMO, this best practice need to be reviewed once again. As the presented solution is definitely and a go-to, out of the box solution.

**Comment by goldbergyoni** [comment]
@sadokmtir Welcome and thanks for bringing this point

To which bullet are you referring? did this guy mention somewhere that 'then probably throwing an error on this global catch' is a good idea?

If I get the point straight, catching global errors is just a measure of safety, last chance to do something useful with an error. Obviously not to re-throw it but make it visible for the developer/ops. Are we on the same channel?
