### ISSUE TITLE
Add API practices

### ISSUE THREAD

**Issue by brillout** [goldbergyoni/nodebestpractices#619]
Hi!

What do you think of adding API practices?

When to use GraphQL, REST or RPC. I'd gladly contribute.

I'm the author of [Wildcard API](https://github.com/reframejs/wildcard-api).

**Comment by goldbergyoni** [comment]
Wildcard looks cool!

What for example should we include in this list given that we try to write on Node.js related things? It shouldn't be too abstract and language-agnostic. I'm afraid that most of the API practices are framework-related

**Comment by brillout** [comment]
I believe the most important would be to teach users which tool to use.

Most devS out there are not sure whether to use REST, GraphQL, or RPC. Anything that shines some light on this would significantly benefit, I believe.

What do you think?

**Comment by goldbergyoni** [comment]
I think that this absolutely valuable piece of knowledge, but outside the scope of this guide. Mostly because there is no best practice for this, it's a big architectural decision that is also not Node related
