### ISSUE TITLE
Should I do module.exports = foo(){} directly?

### ISSUE THREAD

**Issue by sujeet-agrahari** [goldbergyoni/nodebestpractices#650]
Sometimes I need a module to do just one thing.<br><br>
Like, I have a `auth` middleware and its job is to verify that user is authenticated. <br><br>
I don't think any reason there to do follow.
```
const auth = asyn function(req, res, nex) {

}
module.exports = {
   auth: auth
}
```
Instead I like to do 

```
module.exports = async function(req, res, next) {
}
```
What's the problem with my approach?<br><br>
One problem that I have faced. I can't stub `auth` middleware if I do `module.exprts = function(){}`<br><br>
In this case I have to use some other libraries like `proxyquire` just to stub these type of middlewares.<br><br>
What do you guys suggest?<br><br>
Any alternative to achieve the same?

**Comment by goldbergyoni** [comment]
No improvement suggestions, everything you described resonates with me:

When the file is very short, it will be anyway readable and we can take shortcuts. That's fine. I personally keep the same structure (exports last) only for uniformity but that's nitty-gritty. Did we recommend something else in this guide?

About test doubles on direct function export - Proxyquire is indeed the way. I rarely change my code design to ease my testing experience
