### ISSUE TITLE
Polish flag in the homepage

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#674]
@mbiesiad Did we forget to add Polish flag to homepage?

**Comment by mbiesiad** [comment]
@goldbergyoni Good question. Here #631 : https://github.com/goldbergyoni/nodebestpractices/pull/631#issuecomment-606041471 is more info about this. And there is also a snippet for paste. The flag is added to the assets https://github.com/goldbergyoni/nodebestpractices/tree/master/assets/flags and used at the "Completed translations" section (at the end)

**Comment by kevynb** [comment]
Would you mind creating a PR to add it at the top of the homepage like for 🇨🇳 , 🇧🇷 , 🇷🇺  ?

**Comment by mbiesiad** [comment]
Sure, done: #677 -> [changes here](https://github.com/goldbergyoni/nodebestpractices/pull/677/files)

// if the problem occurs again, I will try with the https://emojipedia.org/flag-poland/

**Comment by kevynb** [comment]
Great, thanks @mbiesiad!
