### ISSUE TITLE
Indonesian translation

### ISSUE THREAD

**Issue by kevinstevanus** [goldbergyoni/nodebestpractices#675]
hello, are there any Indonesian translation out there in progress?

**Comment by Yunkou** [comment]
Not yet.

**Comment by kevynb** [comment]
- Selamat datang @kevinstevanus  🎆 !

Having an Indonesian translation could be awesome

Do you want to go for this? Few basic guidelines:

 - Work on your own fork - fork, create a branch, translate & collaborate with other translators, then PR finally
 - Focus on translation, not content editing - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)
 - Duplicate the readme and the inner pages - the content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same
 - Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish)

We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, put homepage banner or anything else

**Comment by kevinstevanus** [comment]
okay I will try do my best, it is my first time to contribute in open source, will try to translate the readme.md first (i forked this project onto my own).
thank you for the help.

**Comment by agmadt** [comment]
Hey, @kevinstevanus any progress? I can help if you want to translate

**Comment by kevinstevanus** [comment]
@agmadt hello there, actually i don't really have time to work with it. 
can you take over the translation ? I will help if i had free time. 
thank you.

**Comment by asyraf-labs** [comment]
@agmadt && @kevinrambaud , any progress for Indonesia translation ??? I'm from  Malaysia, and I know a little bit about Indonesian... I try my best if you need help ;)

**Comment by ahsandev2019** [comment]
any progress for indonesia translator? im ready to join
