### ISSUE TITLE
Kevyn in Steering Committee

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#679]
@kevynb  After speaking with the team, since we all highly appreciate your contributions, tech skills and judgment, we appreciate if you want to join the 'Steering Committee'. 

What does this mean for your routine? not much, same type of involvement, we just think this the right definition of your role (since you're already involved in all discussions and decisions)

What do you think? If resonates with you, kindly PR?

**Comment by kevynb** [comment]
@goldbergyoni and the team, thanks for the offer! It would be a pleasure for me to join the 'Steering Committee'. 😃 

I'll gladly put up a PR to make the change. I might need some time to add the same green circle around my profile pic as you all have 😄

**Comment by js-kyle** [comment]
Thanks for your contributions so far @kevynb !

**Comment by goldbergyoni** [comment]
> I might need some time to add the same green circle around my profile pic as you all have 😄

😆 

@js-kyle You gotta teach us this trick

**Comment by BrunoScheufler** [comment]
This does sound like automation is needed 😄

**Comment by kevynb** [comment]
I used some kind of forgotten and forbidden knowledge to create it (something called copy&paste 😆 )
PR open, see #740
