### ISSUE TITLE
Recommend contract testing on top of having OpenAPI spec and tests

### ISSUE THREAD

**Issue by kibertoad** [goldbergyoni/nodebestpractices#685]
If you have OpenAPI or Swagger spec, and tests for you endpoints, you can have contract testing at virtually no cost.

I can provide a PR for this practice if approved.

**Comment by goldbergyoni** [comment]
I love this.

Can you elaborate a bit on specific tooling? do you refer to consumer-driver or provider-driven contract tests?

**Comment by kibertoad** [comment]
In this case I mean provider-driven testing, when you are simply comparing your responses to your spec to see that they are always compliant; this is different from more heavyweight (but complete) fully end-to-end contract testing Pact-style, but Pareto likely applies here as well.

There's a bit of a problem with available tooling, though. I only see two options that do not require you to setup your app in any different way (e. g. attach middleware) and can be used to augment your existing tests in a non-intrusive way, and neither of them are widely used (precisely because contract testing is not a huge thing in Node.js ecosystem):

https://www.npmjs.com/package/api-contract-validator
https://www.npmjs.com/package/jest-openapi

I think the only widely popular solution is Dredd (https://github.com/apiaryio/dredd), but it is mostly oriented to be used with API Blueprint and Swagger formats, OpenAPI 3.0 support is experimental, and it also doesn't integrate with existing tests, but runs its own by itself.

**Comment by goldbergyoni** [comment]
@kibertoad  I think that we are touching on a very valuable topic which is, as you said, not yet recognized by the Node community.

I highly agree with all your points and add/emphasize some:
1. Provider-driven contracts have great ROI and blend more naturally into a development environment
2. The tools are not there though jest-openapi seems to tick enough boxes. The only requirements is using axios as HTTP client. not that limiting. 

I envision a tool that works differently: Asserting on the contract is not an expectation that should be included in every test rather some mutual property of all testing that is validated on top of the explicit assertions. Maybe by hooking into the HTTP client and validating each response

3. Provider-driven contracts **for the consumer** - There is another use case here: Given the provider contract, also the consumer should verify whether its calls conform to the schema. I found swagger-mock-validator which statically validate our API mock against the schema but not during the tests. Are there better tools? In Java-world there are tools that validate the consumer calls during the tests
 
I would write a bullet, if not a medium post, on this matter. The Node.js community needs this. There is one great article on PACT with Node.js by Liran Tal but we cover it more holistically including provider-driven

**Comment by kevynb** [comment]
That would be a very valuable resource to add to this repo! 
I was looking for something like that not long ago and was wondering how to do it with node only. I had found about Dredd, but as @kibertoad said, it runs by itself.

Your third point @goldbergyoni is also something I hadn't thought of. Quite illuminating!
The worst is with legacy apps, where you might have many undocumented endpoints (if not all). I think that's an area where it could shine
