### ISSUE TITLE
Include MikroORM in the list of recommended ORMs

### ISSUE THREAD

**Issue by kibertoad** [goldbergyoni/nodebestpractices#686]
https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/security/ormodmusage.md

could benefit from including Prisma client (https://www.npmjs.com/package/@prisma/client), which is a popular auto-generated query builder that enables type-safe database access and reduces boilerplate.

**Comment by goldbergyoni** [comment]
Hey @kibertoad, welcome!

Does it stand to our vendor guidelines 👇 

![image](https://user-images.githubusercontent.com/8571500/82753344-8006b080-9dcd-11ea-8c6c-57d63120d691.png)
https://github.com/goldbergyoni/nodebestpractices/blob/master/.operations/writing-guidelines.md

**Comment by kibertoad** [comment]
@goldbergyoni Fair point. Going by these criteria, https://www.npmjs.com/package/@prisma/client sounds like a better option, and I wonder if Waterline should be on the list, it's been a year since it was updated, and I think it is used almost exclusively by Sails.js users.

**Comment by goldbergyoni** [comment]
@kibertoad  Going by those criteria, who are the top 3?
