### ISSUE TITLE
Question regarding your `AppError` example

### ISSUE THREAD

**Issue by coreysnyder04** [goldbergyoni/nodebestpractices#694]
When I read your `AppError` [example here](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/errorhandling/useonlythebuiltinerror.md#code-example--doing-it-even-better) I was super pumped to give it a go. But then I noticed that the errors that were previously being returned to my FE like `"`User doesn't exist`"` were coming to the FE as `An unknown error occurred.`

Here's my exact implementation:
```javascript
function AppError(name, isOperational = false, description) {
  console.log('AppError', name, isOperational)
  this.name = name
  this.isOperational = isOperational
  this.description = description
  Error.call(name)
  Error.captureStackTrace(this)
}

AppError.prototype = Object.create(Error.prototype)
AppError.prototype.constructor = AppError

module.exports.AppError = AppError
```

When I call `throw new Error('No such user found')` the message properly shows up on the FE.

When I call `throw new AppError('No such user found', true, 'No such user found')` it comes through as the wrong error message.

I updated the code to be this instead be
```javascript
class AppErrorClass extends Error {
  constructor(message, isOperational) {
    super(message) // (1)
    this.name = message // (2)
    this.isOperational = isOperational
  }
}
module.exports.AppErrorClass = AppErrorClass
```

And this seems to do the same thing, but it actually sends the original message along as-is. 

So my questions are:
 * Was I doing something wrong in my original implementation? And can I update it to pass along the message? 
 * Is the `AppErrorClass` way better? Are there any caveats to doing it that way? 

I am using 
```
const { GraphQLServer } = require('graphql-yoga')
const { sentry } = require('graphql-middleware-sentry')
```

So maybe one of the two is not liking something about the original implementation?

**Comment by goldbergyoni** [comment]
Hey @coreysnyder04, welcome.

Do these examples help?

[https://github.com/goldbergyoni/nodejs-course/blob/master/examples/error-handling/main-error-flow/error-handler-final.js](https://github.com/goldbergyoni/nodejs-course/blob/master/examples/error-handling/main-error-flow/error-handler-final.js)

[https://github.com/goldbergyoni/nodejs-course/blob/master/examples/error-handling/main-error-flow/error-final.js](https://github.com/goldbergyoni/nodejs-course/blob/master/examples/error-handling/main-error-flow/error-final.js)

[https://github.com/goldbergyoni/nodejs-course/blob/master/examples/error-handling/main-error-flow/api-final.js](https://github.com/goldbergyoni/nodejs-course/blob/master/examples/error-handling/main-error-flow/api-final.js)
