### ISSUE TITLE
JOI link points to package that is not maintained

### ISSUE THREAD

**Issue by Millsky** [goldbergyoni/nodebestpractices#697]
The link to https://www.npmjs.com/package/joi 

Should be updated to point to the maintained version:
https://www.npmjs.com/package/@hapi/joi

**Comment by goldbergyoni** [comment]
Oh, great catch, thanks for that.

If you have 5 min to PR - great. If not, also great, I'll put here a reminder to myself to do this.

/remind me in 7 days

**Comment by Millsky** [comment]
Awesome, thanks @mrjackwills, let me close this one out. The issue has resolved itself!
