### ISSUE TITLE
Feedback before writing: Install npm packages for production (Docker build)

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#699]
Context: This is used to share my TOC of a new best practice so I can solicit feedback and ideas before start writing. From my experience, this makes the writing experience much easier and shorter. And fun.

Title: Install npm packages for production

- TL&DR: When finalizing the docker image for production, a safe package installation should be executed (npm ci) and with only production dependencies
- Otherwise: Dev packages weakness can be used for attacks. Image size is increased for no reason.
- Simple explanation - On the need to ship a safe image to production, what can go wrong with dev dependency (some of the last attacks were on dev packages), what can go wrong when not using 'npm ci', why image size is increased. What if we do need the dev dependency in Docker, how to remove them finally
- Advanced tip - As a bonus, we can also clean the npm cache and reduce the image size even more
- Code example: ```RUN npm ci --production && npm cache clean --force```

Thoughts? improvement? Help me to make it better

**Comment by kibertoad** [comment]
What about `npm set progress=false` if we are talking about CI?

**Comment by goldbergyoni** [comment]
Nice tip, wasn't aware of this command. Is this still useful in latest versions of npm?

**Comment by kibertoad** [comment]
I didn't benchmark it myself; from my understanding it provides a minor boost still, but nowhere near as significant as it was in the past (prior to 3.10.0)
