### ISSUE TITLE
Feedback before writing: Shutdown gracefully

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#705]
Context: This is used to share my TOC of a new best practice so I can solicit feedback and ideas before start writing. From my experience, this makes the writing experience much easier and shorter. And fun.

**Title:** Shutdown gracefully

**TL&DR:** {Still writing}
**Otherwise:** Thousands of ongoing request will not get a response for no reason
**Simple explanation:** Frequently, Docker orchestrators stop and relocate containers as part of their routine tasks; Why? - scale-up, down, refresh, error; why is this important - solely the app responsibility to close thoughtfully, reply to ongoing requests, stop handling new requests, resource release; Why is this challenging - Multiple things happens in parallel, SIGTERM and 30 seconds timers, load balancer at some point will stop serving requests, close webserver but not the existing requests?
**Advanced tip:** Don't start Node via bash command or pm as the SIGTERM won't pass along
**Advanced tip:** What about keep-alive connection, use /npm/stopable
**Code example:** How to gracefully shutdown using Express
**Code example Anti-pattern:** Just log & exit
**Code example Anti-pattern:** Bash & npm start command
**Illustration**: Great drawing of the shutdown process from https://blog.risingstack.com/graceful-shutdown-node-js-kubernetes/

![image](https://user-images.githubusercontent.com/8571500/83753229-94229b80-a672-11ea-81f8-b5f47f034c1b.png)

Thoughts? improvement? Help me to make it better

**Comment by kevynb** [comment]
I don't understand what you mean with ` It's popular ('routine tasks') when this happens`

**Comment by goldbergyoni** [comment]
@kevynb Yeah, that wasn't clear.

Updated text: 'Frequently, Docker orchestrators stop and relocate containers as part of their routine tasks;'

**Comment by kevynb** [comment]
Closing as we merged #716
