### ISSUE TITLE
Feedback before writing: A list of generic Docker practices

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#708]
Context: This is used to share my TOC of a new best practice so I can solicit feedback and ideas before start writing. From my experience, this makes the writing experience much easier and shorter. And fun.

Title: A list of generic Docker practices

TL&DR: A list of generic Docker good practices that are not related specifically to Node

- Don't apt-update or do any modification to the base layer
- Prefer COPY over ADD
- Use unprivileged containers
- Help me with more?

**Comment by js-kyle** [comment]
Leverage build cache https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache

**Comment by kevynb** [comment]
Use a .dockerignore to avoid "uploading" unneeded files in the daemon context

**Comment by goldbergyoni** [comment]
Inspect your built image with image inspectors (e.g. dive)

**Comment by goldbergyoni** [comment]
- Label the image with useful classification
- FROM: should have a tag and it shouldn't be latest

**Comment by goldbergyoni** [comment]
- Integrity check
- Avoid apt-upgrade
- Label

**Comment by kevynb** [comment]
Closing as we merged #722

**Comment by jamonit42** [comment]
Thank you

**Comment by ajimae** [comment]
- Always ensure you check if the full image is what you need or an alpine version of the image, this will save you a lot space.

- Always use multistage build for your images and deployments.
https://docs.docker.com/develop/develop-images/multistage-build/

- Use standard secret management
https://www.docker.com/blog/docker-secrets-management/

**Comment by goldbergyoni** [comment]
@ajimae Thanks for these nice ideas, we already published the Docker best practices section, see on the home page. Given our list, do you think that anything is missing there?
