### ISSUE TITLE
Feedback before writing: Utilize caching for better build time

### ISSUE THREAD

**Issue by kevynb** [goldbergyoni/nodebestpractices#728]
Context: This is used to share my initial draft of a new best practice to get feedback before writing it down.
Title: Leverage caching to reduce build times

- Copy package.json & package-lock first as they don’t change often
- Npm install first, because if package-lock did not change, they shouldn’t have changed -> cache reuse
- Buildx: `Docker buildx build` can push cache to the server, greater cache when build machine come and go (should we talk about this since one has to install docker `buildx` ?)
- Point on using a shared node_modules cache? -> It is usually a bit convoluted. It changes a bit with each CI system. I’m not sure that we should describe it here. Unless you have a bulletproof way of doing it (And I would be more than happy to learn about it), using shared cache in runners is often very slow if you have plenty of dependencies given the overhead of zipping, uploading, unzipping before each run

**Comment by kevynb** [comment]
@goldbergyoni @js-kyle Can I have your feedback on this?

**Comment by js-kyle** [comment]
I think we should probably avoid `buildx` at this stage as it is still an experimental Docker feature

Something which could be good is to include something about avoiding accidentally invalidating the cache, for example adding a label at the top of the Dockerfile which changes

**Comment by goldbergyoni** [comment]
Hey @kevynb , Greta start, couple of thoughts:

1. The main writing challenge - This might be obvious, a good bullet constitutes a short and concise explanation of the basics and then some spice-up and advanced stuff. Don't forget the simple explanation about what layers are, and then try to spice-up and appeal to the senior developer

2. Visuals - There are some nice diagram around which visualize the layers concept

3. Examples - Other cache busters might be test reports, logs, etc. If any of those files is not excluded, than the COPY step will get executed for no reason

4. The reasons for using Buildx sound like overkill for me (cache server)

5. What exactly do you mean by:

> Point on using a shared node_modules cache

?

6. [Dive](https://github.com/wagoodman/dive) is a nice tool that visualizes layer, maybe show a prtscn of a typical Node image layers

**Comment by kevynb** [comment]
I opened #734 

@goldbergyoni for 5. I was talking about the ability to share the node_modules cache by using volume tricks and copying a "cache" folder into the first stage of a multi-stage build. When you have very long node_modules builds it's useful. But I feel like it's overkill for what we're doing 🙃
