### ISSUE TITLE
Do we have an example project to showcase the best practises?

### ISSUE THREAD

**Issue by andremacnamara** [goldbergyoni/nodebestpractices#735]
Hi

Is there a example express application that showcases how to use all the best practises listed in this repo?

**Comment by sujeet-agrahari** [comment]
I don't think there is any example, but I have my own repo which I try my best to implement all the best practices learnt from here.

If anyone want to clone or modify it, a PR is always welcome.

Please have a look, thanks!

https://github.com/sujeet-agrahari/node-express-api-clean-architecture

**Comment by goldbergyoni** [comment]
@andremacnamara Welcome! We would love to create one but fails to find the time. We absolutely plan to. All I can do for now is cross my fingers and share updates 🤞🏽

@sujeet-agrahari Kudos, I'll go over this one soon

**Comment by Imran-S-heikh** [comment]
Yes I am looking for something like this
