### ISSUE TITLE
structuring project according to components

### ISSUE THREAD

**Issue by sujeet-agrahari** [goldbergyoni/nodebestpractices#736]
I have been following all the best practices listed here. Before that I was following responsibility based folder structure.
```
src -
 - controllers
 - models
 - services
```
But now I have folder structure as below.

```
src -
 - auth
 - user
    - address
    - cart
    - order
```
So tried all things related to `/user` in `user` component.

I have a confusion here, should I nest `cart`, `order`, `address` inside `user` as above OR they should be separate ?

**Comment by kevynb** [comment]
Hello and welcome @sujeet-agrahari ! 

That's a good question to which there is no perfect answer 😄 If all those "entities" depend on a `user` laying it out like this on the filesystem looks nice to me. 
I would go with something similar as long as they are dependent on a user (which seems to be the case). If at some point an `order` is something that is used by multiple different entities, then it might be useful to move it to the upper level.

The main idea is that it should make sense to someone opening the project for the first time. It should help highlight how entities work and relate together. 

If you  find yourself `importing` a class from multiple places doing `../../../user/order/myModel` then it might need its own folder at the upper level. This hierarchy is not set in stone, your folders should move around as your requirements evolve.
