### ISSUE TITLE
Always prefer `return await` over `return` when returning a promise

### ISSUE THREAD

**Issue by Alexsey** [goldbergyoni/nodebestpractices#737]
Because of [how fast async stacktraces are implemented in v8 since Node 12](https://v8.dev/blog/fast-async) if promise would be returned from async function without been awaited, and then the promise would be rejected, the created stacktrace would miss the function it was returned from:
```javascript
returnWithAwait().catch(console.log) // will have returnWithAwait in the stacktrace
returnWithoutAwait().catch(console.log) // // will not have returnWithoutAwait in the stacktrace

async function returnWithAwait() {
  return await throwAsync('with await')
}

async function returnWithoutAwait () {
  return throwAsync('without await')
}

async function throwAsync(msg) {
  await null // need to await at least something to be truly async :)
  throw new Error(msg)
}
```
I think the best place for this would be in "2. Error Handling Practices" section as 2.12

In case if the proposal would be approved, I'm ready to create a PR

**Comment by kevynb** [comment]
Hey @Alexsey  It's a long read but it's worth it! Thanks

I don't see why we would object against this since there is a real benefit and that's it's not a trick but a recommendation from the V8 team :)

A PR is welcome 👍

**Comment by goldbergyoni** [comment]
@Alexsey Welcome aboard 🎉

Sounds like a very interesting topic. Very interesting.

Let's discuss this a bit here, refine, extract insights and then plan the PR TOC.

Can you explain to an average developer, me, why the 'returnWithoutAwait' won't get captured in the async trace?

Meanwhile, you may have a look at our [writing guidelines here](https://github.com/goldbergyoni/nodebestpractices/blob/master/.operations/writing-guidelines.md), note that the writing is all about simplifying the ideas and creating short and punchy examples

**Comment by goldbergyoni** [comment]
cc @benjamingr

**Comment by benjamingr** [comment]
Not sure why the ping :] This advice sounds reasonable. 

As far as I know `return` is considered an implicit await point for the purpose of the debugger but not for the stack trace from thrown errors. If you "pause on exceptions" you will see "returnWithoutAwait" there.

**Comment by goldbergyoni** [comment]
@benjamingr I was curious to hear your thoughts:)

**Comment by Alexsey** [comment]
@goldbergyoni thank you :) I'll try to prepare a PR this weekend that would follow the guidelines with a brief but good explanation on why v8 works like that, so recommendation would be supported by some explanations

There is a chance that I'll be able to do it only in a few weeks, so please don't consider potential lack of immediate activity from my side as a lack of interest - just very bussy times :)

On the other hand, if somebody would like to prepare a PR - I would not be offended :)

**Comment by js-kyle** [comment]
It might be worth noting some of the points of when you might not want to use it, see https://eslint.org/docs/rules/no-return-await#when-not-to-use-it-194

**Comment by mikicho** [comment]
> I don't see why we would object against this since there is a real benefit and that's it's not a trick but a recommendation from the V8 team :)

@kevynb can you send a link for the V8 team recommendation? 
Also, if this is always a good practice, why they didn't implement this in the V8 itself? write always `return await` is awkward.

**Comment by Alexsey** [comment]
@mikicho please, take a look at my PR https://github.com/goldbergyoni/nodebestpractices/pull/758 - it includes links on v8 recommendations and explanations on why it works this way. I have tried to explain it at the new added page "Returning promises". Please, take a look, and if you would still have questions I would be happy to extend the PR with answers

The reason why `return` doesn't implicitly awaiting I think (although it's just my thoughts, so I didn't put the into PR) is because `return await` is adding a microtask to the queue, so "zero-cost async stacktraces" would not be truly "zero-cost" in this case

**Comment by mikicho** [comment]
@Alexsey Thanks, very insightful and interesting!!
it's still awkward tho, like without `return await` the application is literally broken. I can't see why it isn't in the v8 itself, but who I am? ;)

**Comment by mikicho** [comment]
@Alexsey Do you think the eslint `no-return-await` is wrong now?

**Comment by Alexsey** [comment]
@mikicho well... it's a very minor performance benefit and a little bit better-looking code vs stacktraces. In case of webserver and CLI tools development, which are the most common way of using NodeJS, I would definitely prefer stacktraces. If your target platform is not running with V8 - the rule is correct. In the end, Eslint is not only about V8 - it's about EcmaScript in general. And of course, I don't want to guess if the author of that rule would create it if "zero-cost stacktraces" were created by the moment he decided to do so

So let's just say that I think it's wrong for NodeJS in 2020 and it looks like other people who respond to this issue agreed

**Comment by mikicho** [comment]
@Alexsey  Maybe it will suite better to https://www.npmjs.com/package/eslint-plugin-node

**Comment by Alexsey** [comment]
There is one edge case that I think worth to discuss: short functions high order functions
```js
const users = await Promise.all(usersIds.map(id => getUser(id, options))
```
and non-anonimous high order functions
```js
const users = await Promise.all(usersIds.map(getUser))
```
In case if `getUser` would throw the `map` would not be in a stacktrace. Considering the fact that `Promise.all` would be in the stacktrace, does it really worth banning this kind of code?

**Comment by benjamingr** [comment]
> In case if getUser would throw the map would not be in a stacktrace. 

Are you sure about that? 

![Uploading Screen Shot 2020-09-21 at 20.08.52.png…]()

**Comment by Alexsey** [comment]
@benjamingr something is wrong with your screenshot - it's not showing. But here is the code to compare stacktraces:
```js
const userIds = [1, 2, 0, 3]
Promise.all(userIds.map(getUser)).catch(console.log) // stacktrace with 2 lines
Promise.all(userIds.map(async (id) => await getUser(id))).catch(console.log) // stacktrace with 3 lines
```
would log 
```
Error
    at getUser ([...]/_.js:7:18)
    at async Promise.all (index 2)
Error
    at getUser ([...]/_.js:7:18)
    at async [...]/_.js:3:39
    at async Promise.all (index 2)
```

**Comment by benjamingr** [comment]
This looks like a regression in chrome that happened sometime in the last few years I think. It doesn't actually require `Promise.all` or array.map to show:

```
{
(async function notAsyncSoDoesNotGetStitched() {
  // remove the await and notAsyncSoDoesNotGetStitched disappears
  return await failAsync();
})()
async function failAsync() {
  await Promise.resolve();
  throw Error();
}
}
```

So I am changing my mind and I agree until this is fixed it is better to recommend `return await`

**Comment by Alexsey** [comment]
@mikicho if there would be an ESLint rule to force `return await` - it would be a good addition for https://www.npmjs.com/package/eslint-plugin-node

But from my shallow understandment of how ESLint works, it's not possible to create such a rule even for all most common cases `return await asyncFunction()` because ESLint works on per-file bases and cannot check if `asyncFunction` is sync or async if it's declaration is located in a different file. Also, there would be absolutely no way to check `return await syncFunctionThatReturnsAPromise` without types

**Comment by kevynb** [comment]
> > I don't see why we would object against this since there is a real benefit and that's it's not a trick but a recommendation from the V8 team :)
> 
> @kevynb can you send a link for the V8 team recommendation?
> Also, if this is always a good practice, why they didn't implement this in the V8 itself? write always `return await` is awkward.

@mikicho sorry for the long wait. I said it was a v8 recommendation because that was my takeaway from the `v8.dev` article linked at the beginning. I might have extrapolated a bit much :)

**Comment by Alexsey** [comment]
@benjamingr the example you wrote is not a bug - this is [how zero-cost async stacktraces **are** working] (https://docs.google.com/document/d/13Sy_kBIJGP0XT34V1CV3nkWya4TwYx9L3Yv45LdGB6Q):

> developers are currently facing the problem that the (non-standard) Error.stack property in V8 only provides a truncated stack trace up to the most recent await

and later

> The solution outlined here utilizes the fact that the promise chains contain sufficient information to continue execution. For await the suspend and resume points coincide and so we not only know where we would continue, but by coincidence we also know where we came from. So we can utilize the information found in the promise chains, specifically the await continuations, to reconstruct a stack trace that contains all the async functions

While in my last example I was trying to bring up some discussion on a special case when missing frames in stacktrace would not affect debug-ability of the code (appeared that they would due to a completely different v8 bug that I linked) but the code may look much nicier. As for me, it's really a shame to ban the code like with non-anonimous high-order function

**Comment by benjamingr** [comment]
> @benjamingr the example you wrote is not a bug - this is how zero-cost async stacktraces are working:

What I meant is that I believe `return` used to be such a "continuation point" for async stack traces (return behaving like return await in that regard). I remember this from talking to Benedikt (who worked on this) and Yang in the Node issue tracker.


Maybe @bmeurer remembers differently? 

---

As a side note - you can dig in the meetings (and follow the trail) here: https://github.com/openjs-foundation/summit/issues/86

**Comment by mikicho** [comment]
So.. this recommendation is valid? there is a "fix" from nodejs in the oven?

**Comment by Alexsey** [comment]
@mikicho the recommendation is valid - the PR with it is just waiting for some final fixes that I hope I'll have time to do this weekend... or next weekend. Unfortunatelly, there is no "fix" from nodejs in the oven and I wouldn't really expect it because it would require changes in v8 that is developing mostly by Google and not the NodeJS team. Also, it would introduce a micro runtime overhead that is irrelevant for web servers but I would not be so sure about other areas where Node is getting used (e.g. embedded)

**Comment by Alexsey** [comment]
Merged!
