### ISSUE TITLE
Add convict to list of packages in "1.5 Use environment aware, secure and hierarchical config"

### ISSUE THREAD

**Issue by ryan3E0** [goldbergyoni/nodebestpractices#738]
In #561/#575, `convict` was added as a bullet point for validating environment variables. Should this also be added to the lines that say "There are a few packages that can help tick most of those boxes like rc, nconf and config"? I was confused because it seemed like `convict` might be a different type of package to use in addition to `rc`, `nconf` or `config` because it was not on that list. But it seems to be similar and could be listed among the other packages to signify that it is an alternative to those.

I'm happy to create a PR, just wanted to get some thoughts and make sure my understanding is correct, thanks.

**Comment by goldbergyoni** [comment]
Yes!

Convict is my favorite config package 💚

**Comment by ryan3E0** [comment]
Thanks! I created a PR for this.

**Comment by kevynb** [comment]
Given that the PR is merged, I'll close the issue :)
