### ISSUE TITLE
Help choosing the header image of our next blog post - Docker best practices

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#739]
The next blog post - Docker practices, is coming in days.

Which is the best theme image?

https://www.shutterstock.com/image-vector/light-bulb-opening-box-many-on-1101551384
https://www.shutterstock.com/image-vector/concept-vector-illustration-kid-sitting-alone-1036401394
https://www.shutterstock.com/image-illustration/stand-out-crowd-different-creative-idea-640038190
https://www.shutterstock.com/image-photo/container-ship-sailing-morning-442557802
https://www.shutterstock.com/image-vector/industrial-sea-cargo-logistics-container-import-1154855923
https://www.shutterstock.com/image-illustration/container-cargo-ship-import-export-business-1398376931

@js-kyle @BrunoScheufler @kevynb

**Comment by kevynb** [comment]
👍  for https://www.shutterstock.com/image-vector/industrial-sea-cargo-logistics-container-import-1154855923

**Comment by goldbergyoni** [comment]
@kevynb Docker articles overuse ships... I prefer this:
https://www.shutterstock.com/image-illustration/stand-out-crowd-different-creative-idea-640038190

**Comment by kevynb** [comment]
Haha that’s true! It’s just that I find those boxes and light look a bit cheap :)
I’ll try to suggest an alternative without a ship :)

**Comment by js-kyle** [comment]
Out of those options I prefer the one Kevyn posted too

**Comment by goldbergyoni** [comment]
@js-kyle @kevynb Let's find then options in shutterstock without a ship?

**Comment by kevynb** [comment]
Going on another topic: the whale!

https://www.shutterstock.com/fr/image-vector/fish-wild-marine-animals-ocean-sea-1488044630
https://www.shutterstock.com/fr/image-vector/sea-light-bulb-world-ocean-day-1545551408
https://www.shutterstock.com/fr/image-vector/people-having-fun-sailing-middle-sea-560674351 (this one has a boat because kubernetes :D )
https://www.shutterstock.com/fr/image-vector/smiling-whale-jumps-on-waves-among-1628688268

**Comment by goldbergyoni** [comment]
@kevynb oopps, saw your message only now. Luckily I did used a whale, though yours are nicer

**Comment by kevynb** [comment]
No worries, let's close this issue 👍
