### ISSUE TITLE
Injecting dependencies from upper scope  vs direct import

### ISSUE THREAD

**Issue by sujeet-agrahari** [goldbergyoni/nodebestpractices#742]
I have a module, let's say `user component` , which has two files `user.controller.js` and `user.service.js`.

`user.controller.js` needs methods from `user.service.js`

Let's take an example.

_user.controller.js_
```
const addUser = ({ doAddUser }) => async (httpRequest) => {
   const user = await doAddUser(httpRequest.body);
   return user;
}
```
_user.service.js_
```
const doAddUser = async ({ firstName, lastName }) => {
  const user = await User.create({ firstName, lastName });
  return user;
}
```
The problem is `user.service.js` needs a `User` instance, what should one prefer here?
1. import the `User` model directly in the service `import User  from './user.model'`
2. inject in the `addUser({ doAddUser, User })` controller along with `doAddUser`
3. user higher order function as in the controller and inject the dependencies from there 
dependencies maybe app level constants, models or helper functions.
```
const doAddUser => ({ User }) => async ({ firstName, lastName }) => {
   const user = await User.create({ firstName, lastName });
   return user;
}
```
Please do drop your thoughts and suggestions, thanks!

**Comment by goldbergyoni** [comment]
Hey, welcome! Interesting stuff.

Thoughts:
1. Controller is a confusing and misleading concept. It does not *control* anything, it meant to be just a thin bridge from the external entry point (e.g. API) to the domain language

2. I prefer to pass commands among layer rather "import" methods

You wrote:

> user.controller.js needs methods from user.service.js

I would say, the controller calls the service/domain

3. The service speaks in the domain language so it should get an entity. The control has one main job - converts the API (for example) format to the domain entity

Based on this, this is my style:

```
//api-entry-point code, "controller" code
const {user, userService} = require('./domain/user');

const userToAdd = user.factor(req.body);
new userService().addUser(userToAdd);
```

I believe this is very simple and expressive. Where does it fall short?
