### ISSUE TITLE
I can help with Spanish translation, can you please tell me how

### ISSUE THREAD

**Issue by Marlond25** [goldbergyoni/nodebestpractices#751]
Hello there, just in case you need some help, i saw it is in progress... let me know.

**Comment by kevynb** [comment]
Hola @Marlond25 welcome to NodeBestPractices and thanks for offering to contribute.

@desko27 is in charge of the spanish translation. Please assign him for review when opening a PR. The PR must be done against the `spanish-translation` branch.

Few basic guideliness:

1. Work on your own fork - fork, create a branch, translate & collaborate with other translators, then PR finally
2. Focus on translation, not content editing - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)
3.    Duplicate the inner pages - the content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same
4. We're here to help - let us know whether we can do anything to support you.
