### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by Luifr** [goldbergyoni/nodebestpractices#766]
Hey!

Who is in charge of the portuguese (pt-Br) translation?
I would like to help

**Comment by kevynb** [comment]
Hey Luifr

It seems that @marcelosdm was the one who initiated the translation in pt-Br. I don't know if he has time available to review portuguese PRs.

Anyway, I'm sure we'll find someone to review portuguese :)

If you want to help, here are some basic guidelines:

 * Focus on translation, not content editing - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)
 * Duplicate the inner pages - the content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.brazilian-portuguese.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same
  
We're here to help - let us know whether we can do anything to support you.

**Comment by marcelosdm** [comment]
Hello guys!

First of all, @kevynb thanks a lot for remembering me!

Well, today I'm available as much as I was when I translated the repository, but I think I can help reviewing the PRs. It'll be very funny!

And @Luifr , your help is welcome! Feel free to start whenever you want!

Be sure to follow the basic guidelines and reach me if you need any help! 🚀🚀🚀

**Comment by goldbergyoni** [comment]
@marcelosdm 🔥

p.s. Side note - Have time and motivation to watch my testing course? it's almost ready and I'm looking for beta viewers

**Comment by marcelosdm** [comment]
@goldbergyoni 
Sure!!!! It'll be awsome!
Count on me!

**Comment by goldbergyoni** [comment]
@marcelosdm My pleasure. Could you mail me or send your email address?

me@goldbergyoni.com
