### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by YukiOta** [goldbergyoni/nodebestpractices#768]
I'd like to help with translating this repo into Japanese(ja-jp) if it's possible.

**Comment by kevynb** [comment]
Hello @YukiOta 

Having a japanese translation could be awesome 🎆 

Do you want to go for this? Few basic guidelines:

   * Work on your own fork - fork, create a branch, translate & collaborate with other translators, then PR finally
   * Focus on translation, not content editing - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)
   * Duplicate the readme and the inner pages - the content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.jp.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same
   * Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish)

We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, put homepage banner or anything else

**Comment by YukiOta** [comment]
Cool! I'm going to get started following the guideline!

**Comment by goldbergyoni** [comment]
@YukiOta Good luck 幸運を! 🚀

**Comment by YukiOta** [comment]
I'm working on translation and almost there, so please keep it open!
