### ISSUE TITLE
Injecting dependency in services in component based structure

### ISSUE THREAD

**Issue by sujeet-agrahari** [goldbergyoni/nodebestpractices#777]
I follow modular or component based strucutre, for that I have also created a sample repo.
https://github.com/sujeet-agrahari/node-express-clean-architecture

So, there is a main `auth.module.js` files which is responsible for connecting all other  pieces like controller, route, and services.

For controller, services are being injected using higher order functions. Now, controller are super easy to test, I can stub or mock services easily.

**auth.module.js**
```
const router = require('express').Router();

const {
  makeExpressCallback,
  makeValidatorCallback,
} = require('../../middlewares');

// validator
const AuthValidator = require('./auth.validator');

// service
const { doRegister, doLogin, doCheckUserExist } = require('./auth.service');

const { BadRequestError } = require('../../utils/api-errors');

// controller
const controller = require('./auth.controller');

const register = controller.register({ BadRequestError, doCheckUserExist, doRegister });

const AuthController = { register };

// routes
const routes = require('./auth.routes')({
  router,
  AuthController,
  AuthValidator,
  makeValidatorCallback,
  makeExpressCallback,
});

module.exports = {
  AuthController,
  AuthService: {
    doRegister,
  },
  AuthRoutes: routes,
};

``````
**auth.controller.js**
```
const register = ({ BadRequestError, doCheckUserExist, doRegister }) => async (httpRequest) => {
  const { username, password } = httpRequest.body;
  try {
    await doCheckUserExist({ username });
  } catch (error) {
    // user doesn't exist
    const registerResult = await doRegister({ username, password });
    return {
      statusCode: 200,
      body: {
        success: true,
        message: 'Registered successfully!',
        data: registerResult,
      },
    };
  }
  throw new BadRequestError('User already exist!');
};

module.exports = { register };
```
Things are fine with the controller, now the problem is with the services. I can't find any pattern to make them thin and clean.

**auth.services.js**
```
const {
  JWT_ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES_IN,
  SIGN_OPTION,
} = require('config');
const bcrypt = require('bcryptjs');
const { User } = require('../../db');
const { generateJWT } = require('./jwt.service');
const { NotFoundError, BadRequestError } = require('../../utils/api-errors');

const doRegister = async ({ username, password }) => {
// create user
  const user = await User.create({ .... });
    // generate access token
  const token = await generateJWT({
    JWT_ACCESS_TOKEN_SECRET,
    ACCESS_TOKEN_EXPIRES_IN
    SIGN_OPTION
    payload,
  });
  return {
    access_token: token,
    ...payload,
  };
};
// other methods should go below

module.exports = { doRegister };
```
A lot is happening in the services, model imports, constants imports, and other utils.

Now services become really hard to test.

Is there any way or pattern I can separate some logic from services and make them lighter?

I can implement repository pattern for db methods, but I am not aware how I can implement using sequelize?

Should I use also higher order function to inject all the utils and constants in the service like I did for controller?

**Comment by sujeet-agrahari** [comment]
@goldbergyoni Do you have any suggestions?

**Comment by goldbergyoni** [comment]
@sujeet-agrahari Welcome aboard, great to have you here.

Please allow few more days as I'm really slowed down by Covid and didn't properly handle previous issues and PRs.

**Comment by sujeet-agrahari** [comment]
@goldbergyoni I can short them sot that they have just one service and controller.

**Comment by goldbergyoni** [comment]
If possible, shorten the service and controller to emphasize exactly the meaningful parts. Only if makes sense. I'll review soon... Sorry for the delay

**Comment by sujeet-agrahari** [comment]
I have shorten the services, controller is already shorten.
