### ISSUE TITLE
Greek Translation

### ISSUE THREAD

**Issue by NikosTsompanides** [goldbergyoni/nodebestpractices#778]
I would like to translate NodeJs Best Practises to Greek language if that's possible :smile:

**Comment by goldbergyoni** [comment]
@NikosTsompanides - Welcome aboard, it's great to have you here 🎆

Having A Greek translation could be awesome! At the end, we can Tweet about this, put in our news section, include your name at the top of the translated language and also at the main home page contributors list

Let's go for this? Few basic guideliness:

- Work on your own fork - Fork this repo, create a branch for yourself, translate & collaborate with other translators, then finally when ready create a PR

- Focus on translation, not content editing - The focus is on translation, should you want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)

- Duplicate the readme and the inner pages - Tthe content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same. You may see examples in currently translated languages

Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish)

We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, put homepage banner or anything else
