### ISSUE TITLE
Any Example Code?

### ISSUE THREAD

**Issue by asherritt** [goldbergyoni/nodebestpractices#779]
Hi guys. I absolutely LOVE this! Please let me know how I can contribute, Patreon, etc.

Redarding: https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/projectstructre/createlayers.md
Do you guys have any example code? I'm not completely clear on what each piece is.

Thanks!

**Comment by goldbergyoni** [comment]
@asherritt Thanks for the kind words 💜

We don't have a proper example. I'm going to have what we do have which is absolutely not good enough and not documented but it's the best we can do for you now.

1. I invited you to a draft repo which outlines some structure
2. This CodePen also shows some folders structure:
https://codepen.io/yonatannn/project/editor/AjLWJz#
