### ISSUE TITLE
Should nodebestpractices have it's own channel under the Nodeiflux discord server?

### ISSUE THREAD

**Issue by josh-hemphill** [goldbergyoni/nodebestpractices#803]
The [Nodeiflux discord server](https://discord.gg/aDsMUFAcmx) is unofficial, but [linked to by Node.js](https://nodejs.org/en/get-involved/#learning)
And it's the only Node communication area besides GitHub that's not for the OpenJSF.
I thought about asking them to create the channel, but thought I'd post here first to see if it'd be welcome.

**Comment by goldbergyoni** [comment]
@josh-hemphill Interesting. How will this look like, people will ask their questions about practices? What opportunity does this bring to us (e.g. being exposed to more discussions)?

**Comment by josh-hemphill** [comment]
Pretty much. Some of the help questions that come through that are along the lines of "what would be best for ___", which could be directed to a channel that's specifically for best practices. (Just brainstorming, but someday we could have a bot that auto-suggests topics from this repo)
It could also be useful for tracking what questions come up that people are seeking out.

**Comment by goldbergyoni** [comment]
@josh-hemphill First, thanks for introducing me to this. I'm exploring it now and seems like a place I'd benefit from visiting occasionally. I'm not sure that we have the capacity for this - We have here issues that are open for too long time without answers. In discord style of communication, one expects an answer in a timely fashion and we might fail to provide that. It could have been really great way to engage continuously with people, we just lack the resources. What do you think?
