### ISSUE TITLE
Adding Winston as a recommended logger

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#810]
@kevynb @josh-hemphill @denisecase

I just noted that we approved the PR logger and Winston was completely removed.

I would propose that it should be on the list, Pino should remain on top, but at least Winston should get mentioned.

Why?
1. It's still the most popular one, this means that many capable engineers give it their trust and it didn't let them down
2. There's nothing fundamentally wrong with it. There are some minor concerns like the file-oriented docs, not optimized performance but it can stand to most missions

Thoughts?

![image](https://user-images.githubusercontent.com/8571500/100434313-f8b03780-30a4-11eb-8cd1-b1b0a9feb076.png)

**Comment by kevynb** [comment]
Agreed!

**Comment by josh-hemphill** [comment]
Yeah, I think providing multiple options is good, provided that we provide sufficient information about their pro/cons and use cases to make it easy for readers to determine which should be used for their use case.

**Comment by swapnil0545** [comment]
I think it should remain out if critical issues are still not addressed with the package. Also, the logger's page has a non-working link(https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/errorhandling/usematurelogger.md#684) mentioned for why winston is removed. Whereas it should have been https://github.com/goldbergyoni/nodebestpractices/issues/684

**Comment by goldbergyoni** [comment]
@swapnil0545  What critical issues?

**Comment by swapnil0545** [comment]
@goldbergyoni  See this comment https://github.com/goldbergyoni/nodebestpractices/issues/684#issuecomment-633242311

**Comment by goldbergyoni** [comment]
@swapnil0545 I see there 1 related issue and asking myself - Is this fair or right to drop a mature OSS project that works great for many because of one issue? In real-estates the property value is estimated mostly by the number of real people that paid real money for similar properties, Winston is the logger of choice for most of the engineers and this tells me more than a single issue

**Comment by josh-hemphill** [comment]
It might make more sense to only mention Winston in the extended document, where we have room to mention it with the caveat that for any logger used, you should not rely on the logger for persistence.
