### ISSUE TITLE
What is the proper way of versioning an express app api

### ISSUE THREAD

**Issue by disapointmntPanda** [goldbergyoni/nodebestpractices#817]
_What is the recommended way of versioning an backend express app so that it is backward compatible, also code be maintainable?_

One way of versioning of api could be as below.
![image](https://user-images.githubusercontent.com/63898013/102049085-40092880-3e06-11eb-934e-86033a086742.png)

But above will created a lot of repeated code, because `v2` might use many services or controller that haven't change hence it will duplicate them in it's own folder structure.

One other way would be to deploy multiple instances based on version in `package.json` and git tags.

**Comment by goldbergyoni** [comment]
What do you hope to solve exactly? Not breaking clients for a grace period? Are those variations exist only in the API front (e.g. route name changed, schema has new field) or also in the internals (e.g. two different implementations should exist forever or for a short time)? Why do you consider committing/deploying two different versions?

**Comment by kevynb** [comment]
Hello @disapointmntPanda, @goldbergyoni reply to issue #826 might give an answer to your question. What do you think?
