### ISSUE TITLE
[request] PDF version

### ISSUE THREAD

**Issue by azev** [goldbergyoni/nodebestpractices#820]
Can we have a PDF format version please?

**Comment by goldbergyoni** [comment]
Hey @azev, Welcome!

I remember there was some PR related to this but failed find it now to follow the status. I wish we had someone coding this but it seems to me that our time can be spent better on stuff like example application, monitoring section, Isn't it?

**Comment by benjakugler96** [comment]
Hi @goldbergyoni ,

I can (or at least try to) create a github page that transforms your main md file to a pdf and let you download it. I can also keep it updated. That will be helpfull? You can just have a link to that github page

**Comment by azev** [comment]
Hey there!

I tried `readme.md` on https://www.markdowntopdf.com but the result is not accurate (see bellow).

Maybe https://www.npmjs.com/package/pdfjs can help us here

![](https://i.imgur.com/baBtXpB.png)

**Comment by goldbergyoni** [comment]
@azev @benjakugler96 Thanks for pushing on this, it seems to be desired by many. Maybe we should combine this with #816 so we use a tool like @josh-hemphill idea to use Docsify and then we may shoot two birds with a single shot - PDF + Item filtering?

The generated PDF above looks very close to be good enough but there are noticeable visual quirks

WDYT?

**Comment by azev** [comment]
@goldbergyoni Thanks. That would be nice too. Every 'Table of Contents' item in a separated PDF. It is basicaly `.md` to `.pdf` conversion. It is not difficult, just need some time to figure out and build it using `pdfjs`.

**Comment by anediaz** [comment]
Hello,
I wanted to create an issue about it too.
It seems many people have the same need. 
I can contribute to this issue.

**Comment by goldbergyoni** [comment]
@anediaz Sounds awesome. Maybe the right way to start is by POCing 2-3 selected tools that can generate some output almost instantly, share the results here, then we can evaluate which looks better and demand less work to finalize?

@rluvaton @josh-hemphill @azev  Any ideas for good candidates?

The following tools were already mentioned:
https://www.markdowntopdf.com
pdfjs
Docsify

**Comment by rluvaton** [comment]
@goldbergyoni if we'll use Docusaurus as suggested in #939 we can use [docusaurus-pdf](https://github.com/KohheePeace/docusaurus-pdf)

**Comment by goldbergyoni** [comment]
Looks like there is no point in using different products for translation and site/PDF, using one tool is the way to go. Added  Docusaurus and @forresst to the list here.

I'd be happy to hear advice on how to proceed

**Comment by rluvaton** [comment]
# Testing
In all the products that I'm gonna tests below and in the following comments I've uploaded the `README.md` file from this repo
File: [README.md](https://github.com/goldbergyoni/nodebestpractices/files/6370513/README.md)


## [MarkdownToPDF](https://www.markdowntopdf.com)
> Bottom line: ❌ 

[output.pdf](https://github.com/goldbergyoni/nodebestpractices/files/6370514/README.pdf)

With an account, you can customize CSS styles.

### Thoughts:
- Poor Markdown converting (some images that are being relative referenced aren't being loaded up)
- Code that is too wide being trimmed with a scroller (maybe can be solved with the custom CSS Styles)

![bad-image+scroll](https://user-images.githubusercontent.com/16746759/115971634-392bb880-a552-11eb-90e1-381e75778716.png)

**Comment by forresst** [comment]
I love it! I will try to provide you with my idea of setting up Docusaurus and Crowdin very soon. Just give me a few days to provide you with this.

I take this opportunity to say hello to @slorber. He is the main maintainer of Docusaurus. And I think his help and advice in setting up Docusaurus would also be useful. (See #939)

**Comment by rluvaton** [comment]
I think that converting markdown into a pdf is highly similar to converting HTML to PDF

(which I **assume** most tools work like this: MD -> HTML -> PDF)

so before jumping on solutions I think we need to define what we **want** from our generated PDF.

> I think programming books (with code) will give us more clue about the end result of some decisions here
>
> Book for example: _Clean Code by Uncle Bob_

This is what I think it's important + some questions:

> I prioritize the things I think are important by 🥇🥈🥉
>
> where 🥇 is the most important and 🥉 is the least

1. 🥇 The Markdown will be fully rendered
2. 🥇 The code will be highlighted and fully displayed
3. 🥇 All images would be displayed
4. 🥈 Links should be kept
5. 🥉 [Bookmarks](https://1.bp.blogspot.com/-xxzQmyE8O80/X_qvU0un-tI/AAAAAAAAVfY/eDFsdtPh07UzQL4A_Yec3_GnvkFxKad9QCLcBGAsYHQ/s1610/chrome-pdf-view.png) (this is the term for table of content in PDF) should exist

### Questions:

#### Sections
1. Will the PDF include the `sections`?
2. If so, where in the PDF?

#### Code

3. Will code in the PDF should be an image or a text? 

##### Image
**Advantages:**
- We can force the image size to fit the page boundaries
- Code won't needed to be broken in them middle

**Disadvantages:**
- if the image is too wide and we still resize it to fit the page width the image would look very small
- If image is being split between pages it can make the code harder to read.

##### Text

**Advantages:**
- the code will have font size that readable.
- the code that span across more than one page will still be readable

**Disadvantages:**
- If the line width is too wide that code would break in order to fit (we need to verify that a word won't be broken in the middle which I think it's unlikely but still)

#### Page _parts_
> I don't call it _sections_ to reduce confusion as I used _sections_ before
>
> Page part is for example, code styles or docker file 

4. Should each part should start at a new page to increase readability (I think it should)


----
Tell me if I've missed something.

N.b if you reached until here you are a true survivor 🏆😉

**Comment by anediaz** [comment]
Hello,
Thank you for such a complete analysis @rluvaton , the only hero here is you!

I've already thought about some of the points you've mentioned, but not all of them, it is amazing!
I have some little remarks :

> > I prioritize the things I think are important by 🥇🥈🥉
> > where 🥇 is the most important and 🥉 is the least
> 
> 1. 🥇 The Markdown will be fully rendered
> 2. 🥇 The code will be highlighted and fully displayed
> 3. 🥇 All images should be displayed
> 4. 🥈 Links should be kept
> 5. 🥉 [Bookmarks](https://1.bp.blogspot.com/-xxzQmyE8O80/X_qvU0un-tI/AAAAAAAAVfY/eDFsdtPh07UzQL4A_Yec3_GnvkFxKad9QCLcBGAsYHQ/s1610/chrome-pdf-view.png) (this is the term for table of content in PDF) should exist
> 

I think the point 4 should be as important as the previous three, with🥇 badge.
What makes this guide rich is its content but also all the articles/quotes/external links it contains, it is important to keep them useful.
 
> ### Questions:
> #### Sections
> > Sections are the extended information written in the `sections` folder
> 
> 1. Will the PDF include the `sections`?
> 2. If so, where in the PDF?
> 

I'd say Yes, but I don't know where, maybe just after each main point?
This is something I've already thought about and the solution is not evident.

> #### Code
> 1. Will code in the PDF should be an image or a text?
> 

I'd complete your comparison (Advantages vs. Disadvantages) with:

- Having the code in a text makes maintaining & updating it easier. If code changes, we are obliged to create a new image of the code
- Plus, if the image of the code does not fit in the same page, we would have to split it to put it in different pages
- We have to consider the guide is translated in 6 languages, there'll be more very soon, and the code images have to be adapted to the layout of each guide

So in conclusion, I personally prefer having the code in text, even if it won't always fit perfectly in one page.

> 
> #### Page _parts_
> > I don't call it _sections_ to reduce confusion as I used _sections_ before (I need to stop explaining _why_ I write stuff, force of a habit 😉)
> > Page part is, for example, code styles or docker file
> 
> 1. Should each part should start at a new page to increase readability (I think it should)
> 

I agree with you, I'd say YES!

> Tell me if I've missed anything.
> 
> N.b if you reached until here you are a true hero 🏆😉

Once again, you're the hero here!

💡➕  Another important point for me (I think it is not been mentioned yet)
this feature should allow generating a PDF from the Markdown of any translated language.
It is important finding a way to identify all the markdown files of a given language to make the conversion into PDF.

Happy to see it is going on 😄

**Comment by anediaz** [comment]
@rluvaton do you need help with this issue?
I think there are many things to do to adapt the current guide for the PDF conversion (i.e. use absolute image paths instead of relative).

I'd be happy to help if you want

**Comment by rluvaton** [comment]
> @rluvaton do you need help with this issue?
> 
> ...
>
> I'd be happy to help if you want

I haven't had much time to work on this issue, I would love help, thank you!

> I think there are many things to do to adapt the current guide for the PDF conversion (i.e. use absolute image paths instead of relative).
>

I think that converting links is already been done in the code in the `.operation` folder

**Comment by anediaz** [comment]
Ok, I can begin by fixing all the paths

**Comment by anediaz** [comment]
Hello,
As recommended by @rluvaton , I've started using Docusaurus for the web site's static generation.
The idea is to generated a PDF from the static web site, when it'll be finished.

For the moment, I've created a small web site to learn how to use it and discover all the possibilities.

https://user-images.githubusercontent.com/17216937/120903462-8cf7ea00-c646-11eb-81b1-da7396adfe53.mov


As you see in the video, I've created a doc called "My first doc": 

- It doesn't contain a sidebar
- There's a code example
- There's a image example

In addition, we can see the default Docusaurus example, called "Intro":

- It contains a sidebar
- The sidebar has simple and collapsable elements

I think I can begin with the migration of nodebestpractices guide to Docusaurus, what do you think about it?

**Comment by rluvaton** [comment]
@anediaz First of all, thank you!


I've tried to create the docs too and observed 3 things:
1. Unclosed HTML tags:
in Docusaurus and because Docusaurus render markdown as React, we need to add closing tags some element that missing (such as `<img>` which in HTML is valid to not be `<img />`)

2. By migrating the docs I think we need to rename our folder names in the section folder to be more _english_ (e.g instead of _testingandquality_ the folder name should be _Testing & Quality_)

3. We should convert all links (images as well) to relative links (the links currently are in `/<folder>/...` format)

4. We need to restructure our translations folder
I've created a `bash` script to generate the folder structure and move the translation files (`create-translations.sh`)
> You should run it from the `docs` folder which will contain this repository content

```bash
#!/bin/bash

# Language code (e.g for Russian it's ru)
LANG_CODE=$1

# Language postfix for the filename (e.g for Russian it was russian - README.russian.md)
LANG_NAME=$2

if [[ ! $# -eq 2 ]] ; then
    echo "Prepare folder structure for language migration"
    echo "Usage: $0 <lang-code> <lang-name>"
    echo ""
    echo "Argumets:"
    echo -e "\tlang-code: Language code of the language you want"
    echo -e "\tlang-name: Language name of the files that already exists in the repo (in case of migration)"
    echo ""
    echo "Example: for Russian - "
    echo -e "\t$0 ru russian"
    exit 1
fi

directories=$(find . -type d -not -path "." -not -path "./i18n" -not -path "./i18n/*" -not -path "./assets" -not -path "./assets/*" -not -path "./.git" -not -path "./.git/*" -not -path "./.github" -not -path "./.github/*" -not -path "./.operations" -not -path "./.operations/*" -not -path "./scripts" -not -path "./scripts/*")

for pathname in $directories; do
  echo "Path: $pathname"
  mkdir -p "i18n/$LANG_CODE/docusaurus-plugin-content-docs/current/$pathname"
done

files_for_language=$(find . -type f -name "*.$LANG_NAME.md" -not -path "." -not -path "./i18n" -not -path "./i18n/*" -not -path "./assets" -not -path "./assets/*" -not -path "./.git" -not -path "./.git/*" -not -path "./.github" -not -path "./.github/*" -not -path "./.operations" -not -path "./.operations/*" -not -path "./scripts" -not -path "./scripts/*")

for filepath in $files_for_language; do
  echo "File path: $filepath"
  filepath_without_language_postfix="${filepath%.$LANG_NAME.md}.md"
  mv "$filepath" "i18n/$LANG_CODE/docusaurus-plugin-content-docs/current/$filepath_without_language_postfix"
done
```

**Comment by anediaz** [comment]
I've already identified the first 3 points you described, and it is cool you've created this bash script.
I'll continue working on it tomorrow, I'll work in the _nodebestpractices_ repository 😄 

Thank you for your help @rluvaton !

**Comment by rluvaton** [comment]
@anediaz I've also created this script to update all the markdown relative links :

note about the implementation It updates the links to be a relative one from the current directory (for the link `assets/...` it will change to `./assets/...`)

This script has the dependencies `markdown-link-extractor`

```js
import * as fs from 'fs';
import markdownLinkExtractor from 'markdown-link-extractor';

// const content = fs.readFileSync('./pg.md').toString();

/**
 *
 * @param {string} text
 */
function updateAllLinks(text) {
  text = updateSrcAttributeThatPointToAbsoluteFilePathToRelativePath(text);

  text = updateAllMarkdownLinks(text);
  return text;
}

/**
 *
 * @param {string} text
 */
function updateSrcAttributeThatPointToAbsoluteFilePathToRelativePath(text) {
  // Regex from https://stackoverflow.com/a/317081/5923666
  const findAttributes = /(\S+)=["']?((?:.(?!["']?\s+(?:\S+)=|\s*\/?[>"']))+.)["']?/g

  const attributes = [...text.matchAll(findAttributes)];
  const onlySrcWithAbsoluteFilePathAttributes = attributes.filter(([_, property, value]) => property === 'src' && !value.startsWith('.') && !value.startsWith('http'));

  text = replaceAllRegexMatches(text, onlySrcWithAbsoluteFilePathAttributes, ([attrWithValue, attr, value]) => {
    return attrWithValue.replace(
      // Same regex as before but with more groups to match the quotes type and more.
      /((\S+)=["']?)((?:.(?!["']?\s+(?:\S+)=|\s*\/?[>"']))+.)(["']?)/,

      // Don't add a prefix slash if already exist.
      `$1.${value.startsWith('/') ? '' : '/'}$3$4`
    );
  });

  return text;
}

function replaceAllRegexMatches(text, matches, replaceFn) {
  // Because we replace the content of the attribute the regex index location for the matched value will changed, so we keep count of the index that needed to be added
  let ogIndexChanged = 0;

  matches.forEach((match) => {
    const updatedValue = replaceFn(match);

    const beforeAttr = text.substring(0, match.index + ogIndexChanged);
    const afterAttr = text.substring(match.index + ogIndexChanged + match[0].length);

    text = beforeAttr + updatedValue + afterAttr;

    ogIndexChanged += updatedValue.length - match[0].length;
  });

  return text;
}

function updateAllMarkdownLinks(text) {
  const details = markdownLinkExtractor(text, true);

  const onlyLinksOrImagesThatAreAbsoluteFilePaths = details.filter(({href}) => !href.startsWith('.') && !href.startsWith('http') && !href.startsWith('#'));

  onlyLinksOrImagesThatAreAbsoluteFilePaths.forEach(detail => {
    let replacedValue = detail.raw;

    const updatedLink = `.${detail.href.startsWith('/') ? '' : '/'}${detail.href}`;

    switch (detail.type) {
      case 'image':
        replacedValue = `![${detail.text}](${updatedLink})`;
        break;

      case 'link':
        replacedValue = `[${detail.text}](${updatedLink})`;
        break;

    }
    text = text.replace(detail.raw, replacedValue)
  });

  return text;
}

const updated = updateAllLinks(content);

// fs.writeFileSync('./pg.md', updated);

```

**Comment by anediaz** [comment]
> @anediaz First of all, thank you!
> 
> I've tried to create the docs too and observed 3 things:
> 
> 1. Unclosed HTML tags:
>    in Docusaurus and because Docusaurus render markdown as React, we need to add closing tags some element that missing (such as `<img>` which in HTML is valid to not be `<img />`)
> 2. By migrating the docs I think we need to rename our folder names in the section folder to be more _english_ (e.g instead of _testingandquality_ the folder name should be _Testing & Quality_)
> 3. We should convert all links (images as well) to relative links (the links currently are in `/<folder>/...` format)
> 4. We need to restructure our translations folder
>    I've created a `bash` script to generate the folder structure and move the translation files (`create-translations.sh`)
> 
> > You should run it from the `docs` folder which will contain this repository content
> 
> ```shell
> #!/bin/bash
> 
> # Language code (e.g for Russian it's ru)
> LANG_CODE=$1
> 
> # Language postfix for the filename (e.g for Russian it was russian - README.russian.md)
> LANG_NAME=$2
> 
> if [[ ! $# -eq 2 ]] ; then
>     echo "Prepare folder structure for language migration"
>     echo "Usage: $0 <lang-code> <lang-name>"
>     echo ""
>     echo "Argumets:"
>     echo -e "\tlang-code: Language code of the language you want"
>     echo -e "\tlang-name: Language name of the files that already exists in the repo (in case of migration)"
>     echo ""
>     echo "Example: for Russian - "
>     echo -e "\t$0 ru russian"
>     exit 1
> fi
> 
> directories=$(find . -type d -not -path "." -not -path "./i18n" -not -path "./i18n/*" -not -path "./assets" -not -path "./assets/*" -not -path "./.git" -not -path "./.git/*" -not -path "./.github" -not -path "./.github/*" -not -path "./.operations" -not -path "./.operations/*" -not -path "./scripts" -not -path "./scripts/*")
> 
> for pathname in $directories; do
>   echo "Path: $pathname"
>   mkdir -p "i18n/$LANG_CODE/docusaurus-plugin-content-docs/current/$pathname"
> done
> 
> files_for_language=$(find . -type f -name "*.$LANG_NAME.md" -not -path "." -not -path "./i18n" -not -path "./i18n/*" -not -path "./assets" -not -path "./assets/*" -not -path "./.git" -not -path "./.git/*" -not -path "./.github" -not -path "./.github/*" -not -path "./.operations" -not -path "./.operations/*" -not -path "./scripts" -not -path "./scripts/*")
> 
> for filepath in $files_for_language; do
>   echo "File path: $filepath"
>   filepath_without_language_postfix="${filepath%.$LANG_NAME.md}.md"
>   mv "$filepath" "i18n/$LANG_CODE/docusaurus-plugin-content-docs/current/$filepath_without_language_postfix"
> done
> ```

Thank you!
This script simplifies us the file restructuring, renaming each README.LANG_CODE.md file to README.md and moving all the files of a language to a specific folder in i18n/LANG_CODE ...

However, it is necessary updating the content of each README in order to transform :
  /sections/projectstructre/breakintcomponents.LANG_CODE.md to  /sections/projectstructre/breakintcomponents.md

Do you agree?

**Comment by rluvaton** [comment]
> Thank you!
> 
> This script simplifies us the file restructuring, renaming each README.LANG_CODE.md file to README.md and moving all the files of a language to a specific folder in i18n/LANG_CODE ...
> 
> 
> 
> However, it is necessary updating the content of each README in order to transform :
> 
>   /sections/projectstructre/breakintcomponents.LANG_CODE.md to  /sections/projectstructre/breakintcomponents.md
> 
> 
> 
> Do you agree?

Yes, but just to make sure, `/sections/projectstructre/breakintcomponents.LANG_CODE.md`  will change to `i18n/LANG_CODE/sections/projectstructre/breakintcomponents.md`

Also, if you change all the files path to relative paths then you won't need to change the links to i18n/... because the structure is the same

**Comment by anediaz** [comment]
> > Thank you!
> > This script simplifies us the file restructuring, renaming each README.LANG_CODE.md file to README.md and moving all the files of a language to a specific folder in i18n/LANG_CODE ...
> > However, it is necessary updating the content of each README in order to transform :
> > /sections/projectstructre/breakintcomponents.LANG_CODE.md to  /sections/projectstructre/breakintcomponents.md
> > Do you agree?
> 
> Yes, but just to make sure, `/sections/projectstructre/breakintcomponents.LANG_CODE.md` will change to `i18n/LANG_CODE/sections/projectstructre/breakintcomponents.md`
> 
> Also, if you change all the files path to relative paths then you won't need to change the links to i18n/... because the structure is the same

Yes I see. This works fine. For the English translation, I've done it manually, as there is no LANG_NAME for English
What I meant is that, for example, on each README we mention the other translations, and the file names are :
README.russian.md, README.chinese.md and so on.

So I guess that for those links, I have to modify the paths manually

**Comment by rluvaton** [comment]
Ohh, so yes
