### ISSUE TITLE
Managing express api version in a modular project structure

### ISSUE THREAD

**Issue by sujeet-agrahari** [goldbergyoni/nodebestpractices#826]
I have following best practices listed on this repo. I went through project structuring guidelines, and issues mentioned there seemed logical. As my project got larger, it was hard to manage the things with `controller`, `routes` and `services` for each component.

So I decided to switch to component/modular structure, it's somehow simplified and now better to handle things. I also was following this repo [here][2]

But now I need to version my api, older version should also be available.

This is my current folder structure.
```
 project
  - node_module
  - src
    - components
      - user
      - auth
      - product
      - customer
      ...
    - middleware
    - utils
    - db
  - package.json
```

I tried to create a `v1` and `v2` directory inside `src` but I ended up a lot of repeated codes, as I need to copy all the things to both `v1` and `v2`

One thing also could be like I deploy two apps using git tags with appropriate versions and setup some API gateway, but this approach is not feasible for me for some reasons.

Please suggest, how can I handle versioning of the api in a better way?

  [2]: https://github.com/sujeet-agrahari/node-express-clean-architecture

**Comment by goldbergyoni** [comment]
What do you hope to solve exactly? Not breaking clients for a grace period? Are those variations exist only in the API front (e.g. route name changed, schema has new field) or also in the internals (e.g. two different implementations should exist forever or for a short time)? Why do you consider committing/deploying two different versions?

**Comment by sujeet-agrahari** [comment]
@goldbergyoni If there is an API let's say `api/v1/auth` that handles auth. I would need another endpoint for changes and modification, `v1` APIs will still be functioning though.

So, `api/v2/auth` will another API.

The question is How should I strcture my app folders so that I can manage versioning better.

Also, there could be a different implementation for the same API in `v2`. Let's say `api/v1/coupons` fetches all the coupons only.

But might be in `v2` , needs all the coupons which are only for that user also for all the users.

So implementation also differes in `v2`.

_Why do you consider committing/deploying two different versions?_
That was just my thought, I wasn't going to deploy that thing. I thought using git version tags.

So, `v1` woudl be deployed on one server and `v2` will be deployed on another server.  An API gateway will route `/api/v1` to version one and vice versa.

**Comment by goldbergyoni** [comment]
Sorry for the late response, here are my thoughts

As a principle - You want to avoid deviates and splitting your app logically and physically at any cost. If you need to support 2 different code bases you increase the maintenance complexity dramatically. Presenting api/vNext/ pushes you toward managing multiple codes, try to avoid this, aim for ONE. How?

1. Stay on one route - If /auth has changes, try to apply them over the existing routes whenever applicable. Have a new field? Be tolerant for clients who don't pass it. If it's mandatory, assign a default value. It might not always be possible...

2. Create a new route - If the change is big, create a new route. Remember and note to clean the old route soon once you can. A new route is much better than a new base API (v2) and from cloing all the folders

3. Adjust the logic - If you need to change the implementation/logic, not only the API layer, change it in a graceful way. For example, users who don't pass the field coupon-id should not benefit the max discount -> Put this logic in your code. Don't create a new code for this. In other words, the core domain of your app should serve all users regardless of the door (API) they entered through

4. Create a totally new API /v/next - This should be done when there is a dramatic change like moving from REST to Graph. Also then, only the outer layer is duplicated, the core stays one and the same

5. Duplicate your entire app - Never I guess

I always push toward simplification, did I oversimplified?

**Comment by sujeet-agrahari** [comment]
@goldbergyoni  Nope, not at all. Thanks to you for taking time and to share your experience. That's what was the aim of the issue  so that I could get some insight rather than trying myself and ending up in a mess. I could have picked one approach either creating `v2` directory or figuring out some other way. But, I also don't like nesting the folder strcuture, suppose if the versions increaze that would create a mess.

**Comment by goldbergyoni** [comment]
@sujeet-agrahari My pleasure
