### ISSUE TITLE
its very usefull but i hope people can give example project

### ISSUE THREAD

**Issue by ahsandev2019** [goldbergyoni/nodebestpractices#828]
i see this is very usefull for me, i want to writing my code in better practices. and this is helping me more.
but can anyone give example project? maybe just todolist is  okey.

**Comment by goldbergyoni** [comment]
Yo @ahsandev2019 , welcome. I plan to do this for 2 years but life had different plans. Let's cross fingers for 2021!

p.s. This will happen eventually

**Comment by ahsandev2019** [comment]
> Yo @ahsandev2019 , welcome. I plan to do this for 2 years but life had different plans. Let's cross fingers for 2021!
> 
> p.s. This will happen eventually

still waiting it hope someone can give real case example

**Comment by rubek-joshi** [comment]
@ahsandev2019 can you reopen this issue so that it gets attention?

**Comment by ahsandev2019** [comment]
> @ahsandev2019 can you reopen this issue so that it gets attention?

bot automatically close it
