### ISSUE TITLE
How shoud I handle errors in nodejs?

### ISSUE THREAD

**Issue by zxciop** [goldbergyoni/nodebestpractices#830]
Im trying to follow this best practice:
https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/errorhandling/centralizedhandling.md

For example, im trying to implement error-handling in my project, written on express\koa.

I have dedicated & incapsulated error-handler:
```
module.exports.handler = new errorHandler();

function errorHandler() {
  this.handleError = async (err) => {
    await logger.logError(err);
    await sendMailToAdminIfCritical;
    await saveInOpsQueueIfCritical;
    await determineIfOperationalError;
  };
}
```

I'll add middleware in the end of all middlewares, following this scheme:
> Some module throws an error -> API router catches the error -> it propagates the error to the middleware (e.g. Express, KOA) who is responsible for catching errors -> a centralized error handler is called -> the middleware is being told whether this error is an untrusted error (not operational) so it can restart the app gracefully.

```
// at the end of all middlewares
app.use((err, req, res, next) => {
    errorHandler.handleError(err);
}
```

Its wrong, however:

> Note that it’s a common, yet wrong, practice to handle errors within Express middleware – doing so will not cover errors that are thrown in non-web interfaces.

The problem is - there are rules how i **should not** implement error-handling, but there are no examples of how i should implement it then. I used middleware with dedicated error-handler before, but after reading this best-practice rules, Im confused where should i place error-handler.

Also "Code Example – a typical error flow" should be marked as "Code Example – Anti Pattern: a typical error flow", if it's wrong, right?

**Comment by goldbergyoni** [comment]
Welcome 🌻!

I see the confusion, the text does not drive the point home. What do we do then? We improve it!

See #843 

Does this answer your question? If not, let's improve the PR together

**Comment by zxciop** [comment]
Everything is perfectly clear now, thank you for explanation!
