### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Ferie** [goldbergyoni/nodebestpractices#837]
I can help with an italian translation, I am an italian mother tongue.

**Comment by kevynb** [comment]
@Ferie - Welcome aboard, it's great to have you here 🎆

Having an italian translation could be awesome! At the end, we can Tweet about this, put in our news section, include your name at the top of the translated language and also at the main home page contributors list

Let's go for this? Few basic guideliness:

-    Work on your own fork - Fork this repo, create a branch for yourself, translate & collaborate with other translators, then finally when ready create a PR

-    Focus on translation, not content editing - The focus is on translation, should you want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)

-    Duplicate the readme and the inner pages - Tthe content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same. You may see examples in currently translated languages

- Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish)

We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, put homepage banner or anything else

**Comment by NPe6** [comment]
![chrome_qrcode_1613660806437](https://user-images.githubusercontent.com/71917928/108900428-76b1ab00-75ce-11eb-80cc-38c71bc098e2.png)

**Comment by NPe6** [comment]
NDTV.com (.cor©navirus). The song "Coronaviros" by the group "The faulten under-wear." (Пающие трусы).
"Coronavirus". The song reminds all of us the importantce of self-isolation and "трусы" preservation in case coronaviros...

**Comment by NPe6** [comment]
[15 years in school. I made it to the 7th grade. I am not getting thrown out now. I've already sent my resume to Palm Desert for a position in their Court House (the Court..- tennis court, tennis court, tennis court - for those, who can remember just one thing in their entire life - Tennis Court - any language - still - tennis court...).](https://m.facebook.com/story.php?story_fbid=669984093622932&id=100018340435008) 

> `
Duplicate of 
 ### 

- [ ] 

> `**@![IMG_1613873656989](https://user-images.githubusercontent.com/71917928/108904098-f04b9800-75d2-11eb-8cfd-ab28a0d49a67.jpg)["Я гимназистка 7го класса, пью ...(?) за место кваса."]() **`

`
