### ISSUE TITLE
Basque translation

### ISSUE THREAD

**Issue by anediaz** [goldbergyoni/nodebestpractices#842]
I can help with Basque translation, the Basque is my mother tongue.
I created this issue a long time ago but I didn't have the time to do it, so the issue was closed (which I find logical).
Now I have more time and I have almost finished the entire translation.

Thanks in advance

**Comment by goldbergyoni** [comment]
@anediaz Welcome back, I remember our conversation well (I still plan to visit the area once Covid leave:)) and happy to see you back. We have a bot that closes issues automatically based on activity. Having Basque translation would be super-awesome, looking forward 🌈

**Comment by anediaz** [comment]
I'll do it certainly this week end.
Could you please remind me the way to contribute ?
I am supposed to fork the repository and after having finished, create a PR, is that right?

**Comment by anediaz** [comment]
Hello everybody,
I've finished the Readme's Basque translation, I'm working on "See more" pages of each section.
I'd like to know if you prefer merging a translation on the very end or you accept publishing partially-translated versions, and in this case I would create a PR.

Thank you in advance,
Ane

**Comment by goldbergyoni** [comment]
Hey @anediaz , It sounds fantastic 💜. If the entire home page is translated, we can merge it and just put the Basque flag in the 'Translation in progress' paranthesis. Make sure to also add your name and the flag. I'll take care to put in news + Tweet + add you to contributors.

**Comment by anediaz** [comment]
Hello,
This is great news! I'll probably create a PR at the end of the day.
The Basque flag is already added in my branch, as well as the "Basque translation in progress" mention at the beginning of each the READMEs, except the Korean and Chinese versions I think (I have to check it out).

I guess I am supposed to add my name at the end of the README, in the "Translations in progress" section. I'd like to include my father's name too, if you don't mind, as he has contributed very actively in the translation.

Should I add my name into "Contributors" part too, or I am mixing "translators" and "contributors"?

**Comment by kevynb** [comment]
Yes you can add a line in "Translations in progress" !
I don't see a reason to oppose adding the name of your father since he participated in the translation 😃 
We have a bot that automatically adds people to the "Contributors" section for their work. As soon as your PR gets merged, we will ask it to add you there

**Comment by anediaz** [comment]
I think we can close this issue
