### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by abderrahmaneMustapha** [goldbergyoni/nodebestpractices#855]
Hello everyone, i would love if I can   help with The Arabic translation, my native language

**Comment by goldbergyoni** [comment]
@abderrahmaneMustapha  - Welcome aboard, it's great to have you here 🎆

Having An Arab translation could be awesome! At the end, we can Tweet about this, put in our news section, include your name at the top of the translated language and also at the main home page contributors list

Let's go for this? Few basic guideliness:

- Work on your own fork - Fork this repo, create a branch for yourself, translate & collaborate with other translators, then finally when ready create a PR

- Focus on translation, not content editing - The focus is on translation, should you want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)

- Duplicate the readme and the inner pages - Tthe content should be translated over a page duplication. Readme.MD became Readme.{translated-language}.MD (e.g. readme.french.md), all other files should be duplicated similarly. So the number of English & translated pages should be the same. You may see examples in currently translated languages

Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish)

We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, put homepage banner or anything else

**Comment by abderrahmaneMustapha** [comment]
hi, @goldbergyoni  thank you for this clear explanation, it helped me a lot to understand how things work here.
and yes if you can  tweet about it or  put a homepage banner
i already forked the repo i will create the new  branch and start working 
thank you

**Comment by goldbergyoni** [comment]
Sounds awesome.

Once the home page will be done we will take care of the promotions (Tweets, banner, etc).

**Comment by HamzaAmar** [comment]
Hello @AbdelrahmanHafez  if you need some help in transition i can help you ?

**Comment by abderrahmaneMustapha** [comment]
@goldbergyoni  thank you , perfect

**Comment by abderrahmaneMustapha** [comment]
> Hello @AbdelrahmanHafez if you need some help in translate i can help you 
Salam @HamzaAmar   yes I need a lot of help there is a lot to translate,  you can contact me on my twitter https://twitter.com/Abderrahmaneend   or email   abdmusttoumi@gmail.com

**Comment by goldbergyoni** [comment]
@abderrahmaneMustapha @HamzaAmar Off-topic - Are development newsgroups/forums popular in Algeria or Morocco and other Arab countries? In other words, do developers just participate in international groups or prefer local groups that speak Arab? If local is preferred, where are those newsgroups typically: Facebook? Discord? Slack?

**Comment by abderrahmaneMustapha** [comment]
@goldbergyoni  we do both we participate in local and international groups and here is some algerian groups : 
 - [dzcode]( https://www.dzcode.io/) go to the bottom of the home page and you will find a link to the slack channel
 - [dzdevs] (https://www.facebook.com/groups/dzdevs) this one is a facebook group
