### ISSUE TITLE
Missing .dockerignore example in the documentation

### ISSUE THREAD

**Issue by anediaz** [goldbergyoni/nodebestpractices#856]
The last part of the README, the Docker-related documentation, there is a 'broken' link.
In the page titled "Use multi-stage builds", which corresponds to the file : https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/docker/multi_stage_builds.md

The `.dockerignore` file is missing, and so the link to access it is broken

**Comment by goldbergyoni** [comment]
Fixed!

Thank you @anediaz :)

**Comment by kevynb** [comment]
Closing this the problem was fixed
