### ISSUE TITLE
don't prettify bad examples :)

### ISSUE THREAD

**Issue by jcayzac** [goldbergyoni/nodebestpractices#866]
It's only 9:25am and I haven't had coffee yet. You got me scratching my head for a while with this 😆 

<img width="315" alt="Screen Shot 2021-02-03 at 9 23 02" src="https://user-images.githubusercontent.com/106682/106680345-d46f5a80-6601-11eb-9a8e-96c20ad11899.png">

Maybe add some `<!-- prettier-ignore -->` before code fences supposed to show bad style?

**Comment by goldbergyoni** [comment]
@jcayzac No doubts that the main issue is reading code without having coffee first. You need day planning linter. You got me laughing.

Can you explain more specifically what made you scratch your head? Share prtscn of the specific part and how it showed on your end? What is the bullet number?

**Comment by elektronik2k5** [comment]
@goldbergyoni the confusing part which @jcayzac is referring to is how the "Do" and "Avoid" blocks are identical due to Prettier formatting it. That's hopefully fixed in #868. Though if Prettier runs on all code then the issue will recur after the merge too. The solution, as @jcayzac suggested is to wrap bad code samples in directives for Prettier to ignore.

**Comment by kevynb** [comment]
The thing is, why did prettier ran on the `README.md` ? 🤔  There's no build or github action in this repo.
If we add `<!-- prettier-ignore -->` They are going to show up in the code examples and add noise to it.

Do you know if there is a way to globally disable prettier for a repo?

By the way, I agree with your point about removing some BP that are always handled by eslint or prettier. I wouldn't weight for one over the other though.

**Comment by SuspiciousLookingOwl** [comment]
> The thing is, why did prettier ran on the `README.md` ? 🤔 There's no build or github action in this repo.
I think someone was using IDE / Code editor with code formatter while editing the file and accidentally formatted it.

I'm using VSCode and had the file formatted by prettify too because I have:
```json
{
  "editor.formatOnSave": true,
  "[markdown]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  ...
}
```
on my global `settings.json`

I prevented this by creating `.vscode/settings.json` file, containing
```json
{
  "[markdown]": {
    "editor.defaultFormatter": null
  },
}
```

**Comment by rluvaton** [comment]
@SuspiciousLookingOwl You should create a PR with that change...

**Comment by SuspiciousLookingOwl** [comment]
@rluvaton Problem is, `.vscode` is in `.gitignore`, for reasons that I don't know yet.

**Comment by rluvaton** [comment]
> @rluvaton Problem is, `.vscode` is in `.gitignore`, for reasons that I don't know yet.

That's what I usually do too (IDE config isn't related to the project, but this time it does)...

**Comment by jcayzac** [comment]
Hi,
This has nothing to do with `.vscode`. This is the correct what to declare a code fence in markdown with Prettier disabled:

~~~md
### Code Example

<!-- prettier-ignore -->
```javascript
// Do
function someFunction() {
  // code block
}

// Avoid
function someFunction(
{
  // code block
}
```
~~~

Markdown supports HTML, so HTML comments like `<!-- prettier-ignore -->` are of course never rendered.

**Comment by elektronik2k5** [comment]
Another option is to add a `.prettierignore` file at the root of the project with `README.md` in it (along with any other files/globs which we wanna skip).

**Comment by jcayzac** [comment]
You don't want the markdown prettified? This is bad for something supposed to show best practices (I was actually surprised when someone earlier said the project doesn't use prettier).

**Comment by goldbergyoni** [comment]
@jcayzac Prettier is great for aligning team standards, I'm not sure it's that great for educational purposes. 

Sometimes during workshops/talks I try to present some code examples, 5 statements only, simple stuff, with prettier it gets 20 lines that scare the audience.
