### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by marcosmol204** [goldbergyoni/nodebestpractices#888]
Hello!
I would love to contribute with Spanish translation. It could be possible ?

**Comment by goldbergyoni** [comment]
@marcelosdm Welcome!1!@

@desko27 is the lord of this who already did tremendous work, he can probably suggest where exactly your contribution be most valuable

I know that @jormaechea has also worked on this recently 🚀

**Comment by marcosmol204** [comment]
Hi @desko27 @jormaechea , can you contact me and tell me what I can translate. 
My email is marcosmol204@gmail.com
Muchas gracias in advance.
Marcos

**Comment by jormaechea** [comment]
Hi @marcosmol204 

I started from the issue linked in the README (#95 -- closed) and then created a PR (#769) where I fully translated sections 1 and 2.

I think that you can keep it going from section 3

**Comment by desko27** [comment]
Hi @marcosmol204, thank you for showing interest in contributing. I don't have the time I used to, but I can help with a PR review once you're done translating. There is a [branch for spanish translation](https://github.com/goldbergyoni/nodebestpractices/blob/spanish-translation/README.spanish.md) so anything you find untranslated there can actually be translated by anyone who is willing to.

**Comment by JhonRobert20** [comment]
Hi! @jormaechea @desko27 , Can I help with the spanish translation? I will be happy to help anywhere. Thank you!

**Comment by JFernando122** [comment]
Hi @desko27 i would like to contribute on the spanish translation. Is there any specific file you would like me to start working on?, or should i go translate whatever i see is missing?
Thank in advance.

**Comment by goldbergyoni** [comment]
Welcome aboard @JhonRobert20 @JFernando122 🌻

**Comment by JFernando122** [comment]
Thanks @goldbergyoni  i'll start as soon as posible, only one thing...

It's my first contribution to a big project and i see that the spanish-translation branch is like 1.8k commits behind master, and i don't know what to do in cases like that, do i merge/rebase master and the start working on it?, or what do i do?

**Comment by goldbergyoni** [comment]
@desko27 Is spanish-translation branch still the place where we push spanish contributions to?

@JFernando122 Yes, merge/rebase seems sensible and inevitable, can you do a quick try to see how many conflicts exist?

**Comment by JFernando122** [comment]
This is what i get on VSCode.

![image](https://user-images.githubusercontent.com/40414805/118408600-e6728780-b64b-11eb-97bd-a03cf8d50720.png)

![image](https://user-images.githubusercontent.com/40414805/118408641-13bf3580-b64c-11eb-9c6e-0cce89239edb.png)

![image](https://user-images.githubusercontent.com/40414805/118408652-22a5e800-b64c-11eb-897e-122500985ee9.png)

![image](https://user-images.githubusercontent.com/40414805/118409098-75809f00-b64e-11eb-9ddd-6423a09f9805.png)

What i found weird is that in there shows that the spanish files are in korean, but when i look on the files before rebasing, they are in spanish

**Comment by JhonRobert20** [comment]
Hello, sorry now, not the time I had when I wrote the previous time, thank you very much anyway. Sorry for the inconvenience

**Comment by goldbergyoni** [comment]
@JFernando122 Only 1-2 conflicts? If yes, I would not spend time on this. Just override the file with the English version and or a Spanish one if there was one ever

**Comment by JFernando122** [comment]
Sorry for the long time.
I rebased and make some work to push, but don't know if i did it properly.
![image](https://user-images.githubusercontent.com/40414805/124512220-7657c680-dd9d-11eb-93d7-51fe5b033327.png)
Since i did the rebase it appears like 2k+ new commits but the actual changes are in the last 3 commits.
Just wanting to make sure i'm doing it right before making a bad pull request.
Again sorry for the inconvenience

**Comment by GeekBeardLinks** [comment]
Hi! I found out about this project today. Happy to help with the translation!

Although there is a lot of work to do, from what I could see 48 files in English changed from the arm in Spanish that were translated and 32 new files that have not been translated yet.

**Comment by GeekBeardLinks** [comment]
Hi! I made MR #1031 to update spanish-translation branch with master. I do not made a rebase, just a plain old merge from master to the spanish-translation.

**Comment by JFernando122** [comment]
@GeekBeardLinks I already have updated translations for the sections(just waiting for you merge to go trough so i can add onto that):
- main README.spanish.mg and writting-guidelines
- errorhandling
- performance
- production
- testingandquality

The sections that still need an update are:
- codestylepractises
- docker (completly missing all spanish translations)
- projectstructure
- security

**Comment by marcelimxo** [comment]
Hi! I found this project and I would love to help with the translation but I see that you have some work in progress but it's not very clear which parts are complete or not, can you let me know what is missing so I can help?

**Comment by GeekBeardLinks** [comment]
@goldbergyoni @BrunoScheufler @kevynb can you help us moving this forward? Fernando is waiting the spanish translation branch with PR #1031 to be updated to add his changes. Thanks!

**Comment by rluvaton** [comment]
> @goldbergyoni @BrunoScheufler @kevynb can you help us moving this forward? Fernando is waiting the spanish translation branch with PR #1031 to be updated to add his changes. Thanks!

Thank you for being here! I'll ask someone to review it

**Comment by rluvaton** [comment]
Done, @JFernando122 you can now continue 😀

**Comment by goldbergyoni** [comment]
@JFernando122 @rluvaton 💜
