### ISSUE TITLE
Use Require status checks to pass before merging

### ISSUE THREAD

**Issue by rluvaton** [goldbergyoni/nodebestpractices#896]
I see you use Travis.CI, I advise you to use the [Require status checks to pass before merging](https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule)

**Comment by goldbergyoni** [comment]
Great idea @rluvaton ! I'll take care to do this very soon

**Comment by rluvaton** [comment]
@goldbergyoni Also, the tests only run in forks repos and not in this one

**Comment by goldbergyoni** [comment]
@rluvaton I suggest moving the CI to GH, our maintenance work would be much easier
