### ISSUE TITLE
How to best handle error generated by node or libraries like joi during schema validation?

### ISSUE THREAD

**Issue by iJKTen** [goldbergyoni/nodebestpractices#902]
I created this class 

```
class HttpError extends Error {
    constructor({ msg, name, statusCode, data }) {
        super(msg);
        this.name = name;
        this.statusCode = statusCode;
        this.data = data;
        Error.captureStackTrace(this, HttpError);
    }
}

module.exports = HttpError;
```

and in my app I can now raise HttpError with a status code and a message and I didn't create any other classes like HttpNotFound because then I would end up creating an error class for each status code and that will not help with anything. 

Raising errors this way is perfectly fine according to the best practices. 

Question, how do I handle errors thrown my Node, mongo, or libraries like joi when I perform validation, for example

```
try {
            const value = await loginSchema.validateAsync(req.body);
            req.validatedBody = value;
            next();
        } catch (err) {
            next(err);
        }
```

The above error is not an HttpError but an Error. Now the best practice is being violated because I am not using one single Error class. 

Thoughts?

**Comment by HamzaAmar** [comment]
hi @iJKTen for me what i do is to check the err if validation err in the catch block 



```
catch (err) {
        if(err.name === 'ValidationError'){
           do what you want here
        }
        next(err);
}
```

**Comment by goldbergyoni** [comment]
@iJKTen About how many error objects ("I am not using one single Error class") - Obviously we can't ensure that only our errors reach to the handler, but we can minimize others in 3 ways:

* Your code throw HttpError
* Your express handler wraps unknown errors with HttpError (status:500), so the handler always gets your HttpError from the middleware
* At specific code locations where you care for specific custom error (e.g. validation), you may catch and re-throw with HttpError like in the Joi example. It's also valid to just return 400 there without error

You didn't include isTrusted property to your error which I think is important, see related BP

@HamzaAmar About helper libraries - You can use those with your own custom error, just use them as enumeration for the status code and/or create a factory that returns many error types

**Comment by iJKTen** [comment]
Awesome. Thanks for the feedback!
