### ISSUE TITLE
Best practice of using 'instanceof'

### ISSUE THREAD

**Issue by ZhyMC** [goldbergyoni/nodebestpractices#918]
Tip: set '.isXXX' as a property of object instead of using the keyword 'instanceof' to identify if an object is an instance of a class

Why: because the prototype chain of an object is not serializable commonly, so if you need to transfer the object through the network, like using RPC framework, a property is the best way to check the relationship between instances and classes.

**Comment by ZhyMC** [comment]
let's discuss it

**Comment by ericblade** [comment]
if you send the object's underlying data through to something else, then you don't have an instance of a class on the other side, until you rehydrate it into a class instance.  instanceof is unrelated to "is this data that could belong to an instance of".

**Comment by goldbergyoni** [comment]
@ZhyMC Welcome aboard:)

My thoughts: Generally speaking, Classes and prototypes are used for internal design purposes, not to externalize information. In reality, there are indeed cases where developers create classes to classify objects - A popular example is Errors where instead of adding an identifying property "name" or "code" to an Error object, developers create an inheritance tree (e.g. ValidationError extends CustomError). This is not helpful to external API clients who can not reason about the error type now.

If you have other *common* examples then we can consider this as a general BP, otherwise it seems like a design suggestion for Error objects?

**Comment by ZhyMC** [comment]
@goldbergyoni oh, You are really experienced. In fact, i got this point of setting a property named 'isXXXX' when i was developing an RPC framework [ZhyMc/jigsaw-rpc](https://github.com/ZhyMC/jigsaw-rpc). I tested many cases and found that a property to identity the type of an Error is better than using the keyword 'instanceof' due to serialization. So, I think that if this point can be extended to all situations. Thanks for telling me that prototypes are not used to externalize information. i will consider it into my projects' design. So can we reconsider it as a best practice of transfer an Error object through the network?

**Comment by ZhyMC** [comment]
> Classes and prototypes are used for internal design purposes, not to externalize information. In reality, there are indeed cases where developers create classes to classify objects

Is my understanding correct?  

In the internal field of a project, we can easily use prototypes to check the type of a class, ``instanceof`` is design for this. But many developers don't notice this. So they use prototypes in purpose of making prototypes provide the information from its internal design.

**Comment by ZhyMC** [comment]
> instanceof is unrelated to "is this data that could belong to an instance of".

@ericblade OK, i get it

**Comment by goldbergyoni** [comment]
> In the internal field of a project, we can easily use prototypes to check relationship between instances and classes, instanceof is design for this. But many developers don't notice this. So they use prototypes in purpose of making them provide information from its internal design

@ZhyMC Kind of, I would say that anytime you want to externalize some info - Assign an explicit property to the object which is not related to how the code is designed. As you actually suggested in the beginning of this thread:)
