### ISSUE TITLE
Broken external links

### ISSUE THREAD

**Issue by anediaz** [goldbergyoni/nodebestpractices#927]
Hello,

I've recently realized some external links included in this guide are broken.
I am aware this is not your fault, but I thought it was worth telling you, you may want to replace them.
This is the list of identified broken links :

- [5.1 Monitoring](https://github.com/anediaz/nodebestpractices/blob/master/sections/production/monitoring.md): [The Rising Stack](http://mubaloo.com/best-practices-deploying-node-js-applications/) link
- [5.3 Delegate proxy](https://github.com/anediaz/nodebestpractices/blob/master/sections/production/delegatetoproxy.md): both [Mubaloo](http://mubaloo.com/best-practices-deploying-node-js-applications) and [Argteam](http://blog.argteam.com/coding/hardening-node-js-for-production-part-2-using-nginx-to-avoid-node-js-load) links
- [5.10 Measure and guard the memory usage](https://github.com/anediaz/nodebestpractices/blob/master/sections/production/measurememory.md): [Dynatrace blog](http://blog.argteam.com/coding/hardening-node-js-for-production-part-2-using-nginx-to-avoid-node-js-load) (2nd & 3rd links)
- [6.5 Collection of generic security best practices](https://github.com/anediaz/nodebestpractices/blob/master/sections/security/commonsecuritybestpractices.md): [Singapur](https://www.pdpc.gov.sg/Legislation-and-Guidelines/Personal-Data-Protection-Act-Overview) link
- [6.10 Validate incoming JSON schemas](https://github.com/anediaz/nodebestpractices/blob/master/sections/security/validation.md):  [Gergely Nemeth's blog](https://nemethgergely.com/nodejs-security-overview/)
- [6.11 Support blacklisting JWTs](https://github.com/anediaz/nodebestpractices/blob/master/sections/security/expirejwt.md): [Marc Busqué](http://waiting-for-dev.github.io/blog/2017/01/25/jwt_secure_usage/)'s blog
- [6.24 Prevent unsafe redirects](https://github.com/anediaz/nodebestpractices/blob/master/sections/security/saferedirects.md): [Hailstone's blog](https://blog.hailstone.io/how-to-prevent-unsafe-redirects-in-node-js/)

**Comment by goldbergyoni** [comment]
@anediaz wow, great catch! This will get handled shortly.

Hopefully anyone who sees this and plan to PR soon, fix just one link:)

p.s. Basque translation PR is coming very soon, didn't forget of course!

**Comment by lucalves** [comment]
Hello @anediaz, I dedicated myself to searching for the right links on the internet and found some. I opened PR #953, which corrects this. However, it does not resolve all of the links you mentioned above.

**Comment by anediaz** [comment]
Hi @lucalves,
This is great! You have managed to find the right links (almost all of them) and replace them in all the languages.
I can try to look for those that are missing, maybe I have a chance.

Let me know :-)
Great work!
