### ISSUE TITLE
Wrong code example at 3.3 Start a Codeblock's Curly Braces on the Same Line

### ISSUE THREAD

**Issue by burkybang** [goldbergyoni/nodebestpractices#936]
The 2 examples here are identical. The second one should have the opening curly brace on the next line.

https://github.com/goldbergyoni/nodebestpractices#code-example

**Comment by rluvaton** [comment]
@goldbergyoni I though we solved this issue already, why it keeps coming?

@elektronik2k5 any idea?

**Comment by burkybang** [comment]
I was on mobile previously, and for some reason it wasn't letting me create a PR. I just created it.

**Comment by anediaz** [comment]
Hi,
Sorry for the late answer. 
I've used VSCode to do the Basque translation. 
Tell me, what it is giving you problems with what I've pushed, I'd be glad to help you 😊

**Comment by rluvaton** [comment]
> Hi,
> 
> Sorry for the late answer. 
> 
> I've used VSCode to do the Basque translation. 
> 
> Tell me, what it is giving you problems with what I've pushed, I'd be glad to help you 😊

@anediaz Thanks for replaying, when you wrote the translation I guess that VSCode did some auto format for the markdown files.

1. Can you please check how to disable this in VS code and commit the vs code setting file?

2. Can you please check in your PR which changes hasn't done by you (from your PR I saw some changes in other translations too)

**Comment by anediaz** [comment]
I'm at work right now, I don't have my computer with me.
I'll give you all this information at the end of the day if you don't mind.

Sorry for the trouble :-(

**Comment by anediaz** [comment]
Do you think it could be this setting ?
![Capture d’écran 2021-03-30 à 19 55 35](https://user-images.githubusercontent.com/17216937/113034082-ff090a00-9191-11eb-8929-95f2e7d918f4.png)

to be changed into 

![Capture d’écran 2021-03-30 à 19 55 43](https://user-images.githubusercontent.com/17216937/113034110-06301800-9192-11eb-9265-a95f29d64af9.png)

**Comment by rluvaton** [comment]
> Do you think it could be this setting ?
> 
> ![Capture d’écran 2021-03-30 à 19 55 35](https://user-images.githubusercontent.com/17216937/113034082-ff090a00-9191-11eb-8929-95f2e7d918f4.png)
> 
> 
> 
> to be changed into 
> 
> 
> 
> ![Capture d’écran 2021-03-30 à 19 55 43](https://user-images.githubusercontent.com/17216937/113034110-06301800-9192-11eb-9265-a95f29d64af9.png)
> 
> 

It doesn't seem like it from the [docs](https://prettier.io/docs/en/options.html#prose-wrap) but maybe, you can test it and see if it format or not

**Comment by anediaz** [comment]
The fact is that I haven't understood which is the issue 936, so I'm not sure to be able to assure if it's ok or not.
Can you explain it to me please?

**Comment by rluvaton** [comment]
> The fact is that I haven't understood which is the issue 936, so I'm not sure to be able to assure if it's ok or not.
> Can you explain it to me please?

Of course, this issue is about [3.3 Start a Codeblock's Curly Braces on the Same Line](https://github.com/goldbergyoni/nodebestpractices#-33-start-a-codeblocks-curly-braces-on-the-same-line) which talks about why you should start a curly braces on the **same line**, and provide an example:

```javascript
// Do
function someFunction() {
  // code block
}
// Avoid
function someFunction() {
  // code block
}
```
but as you can see the `Do` and the `Avoid` are identical, this is because the _avoid_ should be like this:
```js
// Avoid
function someFunction()
{
  // code block
}
```

We think (because it happened already) that some editor autoformat this code block and we saw that it changed in your PR.

If you like another explanation, I'll be happy to explain it 😄

**Comment by anediaz** [comment]
Ohhhh I see!!
The difference is so minimal I couldn't find it.
Don't you think it is a mistake I've made explicitly, nothing related with code or markdown formatter?

**Comment by rluvaton** [comment]
Maybe you're right, I looked over your PR's files and saw that nothing else was affected...

**Comment by anediaz** [comment]
Yes, and besides, I don't find any `vscode settings` file on my workspace or on the PR files

**Comment by burkybang** [comment]
Is this one resolved? Can we close it?

**Comment by rluvaton** [comment]
> Is this one resolved? Can we close it?

https://github.com/goldbergyoni/nodebestpractices/pull/937#issuecomment-817353542
