### ISSUE TITLE
[Suggestion] Use a dedicated tool to help with the translations 

### ISSUE THREAD

**Issue by rluvaton** [goldbergyoni/nodebestpractices#939]
# The problem
The problem is that:
1. Don't have a way to track what's been already translated and what left (Which can help new contributors to know what's missing)
2. Track when some content changed where it need to also be changed
3. When we update a code snippet (or formatting) we need to update every translation

# The Solution
Use a dedicated tool to manage the translation for you.

## Product
I've only tested [GitLocalize](https://gitlocalize.com/) and it looks pretty good (It solve only the first 2 problems though).
> My repo that I did the testing is available [here](https://github.com/rluvaton/playground-gitlocalize) and the GitLocalize Project is [here](https://gitlocalize.com/repo/5969)

### Advantages
1. Free
2. Have Integration with GitHub (Can create commits and PRs).
3. Track translation progress.
4. Synced with changes in `master` (or any other branch you want) so when updating
5. The new file structure is more organized as you don't need to search for your language code for every file.

### Disadvantages
1. We may need to change the location of the translation files (but I think it will be way more organized in the new way) (or you can add manually the files which is not really an option as it brings too much work to maintain that list)
2. When some changes happen in the `master` branch on the file you currently translated, the translation for this file will be removed (But you can restore it easily and updated with the changes)

-----
WDYT?, If someone has other tools I'll be happy to hear about them.

**Comment by forresst** [comment]
**Another solution**: [Docusaurus](https://docusaurus.io/) coupled with [Crowdin](https://crowdin.com).

> Note: The Docusaurus documentations are themselves translated with Crowdin

## Advantages

1. See the [features](https://docusaurus.io/docs/next/#features) of Docusaurus V2 to know the advantages of documentation layout and more (search, Document Versioning, I18n, ...). Browse the Docusaurus documentation site to see the design and useful features.
2. Free
3. Have Integration with GitHub (Can create commits and PRs).
4. Track translation progress with Crowdin. (Crowdin is free for the Open-Source projects)
5. Synced with changes in master so when updating
6. The new file structure is more organized as you don't need to search for your language code for every file
7. When some changes happen in the master branch on the file you currently translated, the translation for this file will be **keeped** in Crowdin
8. All untranslated texts remain in the original language
9. Crowdin is simple and intuitive to use. It also includes translation suggestions, which can help translators. Possibility to add glossaries for each language (useful to respect a uniformity of translations made by several people) and it is even possible to add context to help translators

## Disadvantages

1. We may need to change the location of the translation files
2. It may be necessary to re-translate everything, I'm not sure it's possible to reintegrate all the translations already done. This point remains to be checked.

Personally, as I know these two tools better, I am more in favour of the solution I propose, but I am obviously interested in your opinion.

**Comment by rluvaton** [comment]
@forresst I'm not locked on a product, if you are familiar with both of them I trust your decision.

**Comment by forresst** [comment]
For the Docusaurus/Crowdin solution: 

> ## Disadvantages
>
> ....
> 2. It may be necessary to re-translate everything, I'm not sure it's possible to reintegrate all the translations already done. This point remains to be checked


It is confirmed, the translations must be redone, consult the [crowdin FAQ](https://support.crowdin.com/enterprise/common-questions-managers/#how-do-i-upload-my-existing-translations-to-crowdin)

**Comment by goldbergyoni** [comment]
@forresst What does 'redone' exactly means? Just add a new language, copy-paste the existing translations and commit or more than that? If this task is highly repeatable and straightforward, I'm working with data-entry agency that can handle this

**Comment by forresst** [comment]
@goldbergyoni This is the principle: 
1. In Crowdin, you add the different markdown files to translate
2. Crowdin cuts each sentence into a string to translate
3. Still in Crowdin, a user chooses in which language he wants to translate
4. The user must translate each sentence one after the other.

So if I take the example of the doc already translated into French, I would have to copy all the sentences from the Markdown files translated into French to Crowdin one after the other (sentence). It's not complicated, just a little bit tedious. But it's not a problem for me (I'll do it without any problem for the French part). I admit that anyone can do it, but knowledge of the target language can simplify the task.

I put this point in disadvantages because it is a job to be done, there is no magic solution! But this is a one-off job.

**Comment by slorber** [comment]
Hi

You can find some interesting links on the Docusaurus i18n RFC on strategies used by some large documentations
https://github.com/facebook/docusaurus/issues/3317

I think @clairefro tried to use GitLocalize for
https://learn.redwoodjs.com/ but it was not good enough. 

Crowdin is not the best looking translation saas out there, and certainly have some rough edges and weird UX, but is free for open-source and gets the job done in our experience. It is particularly helpful when the English docs are updated as it will keep in sync all the localized docs with the upstream changes. 

@forresst there's an upload translation feature on the Crowdin cli that you can use to prepopulate a Crowdin project with some existing translations. It is not their most reliable feature (particularly for markdown content) so you may need to manually fix some errors.

**Comment by anediaz** [comment]
Hi,
I find this is a very important feature that could improve tremendously the language management.
I've recently finished the guide's Basque translation and I was figuring out how to follow and manage all the futur modifications.

So I'm really happy you've thought about this problematic.
Thank you!!

**Comment by jahelo** [comment]
How is the status with this? I would love to contribute a German translation and this sounds like a Great idea that would simplify the sync of the translation.

**Comment by rluvaton** [comment]
Hey, thank you for your will to contribute, we're in the middle of migrating to Docusaurus which hopefully help us with the translation process, you can start translating the old way and we'll catch up in the middle
