### ISSUE TITLE
update the translation for password hashing as it renamed and updated

### ISSUE THREAD

**Issue by rluvaton** [goldbergyoni/nodebestpractices#942]
When worked on #941 I found out that the file `sections/security/bcryptpasswords.md` is missing but his translations exist, so maybe it was deleted but the translations haven't?

**Comment by josh-hemphill** [comment]
It was renamed and rewritten in #788

**Comment by josh-hemphill** [comment]
I'm going to tag #939 here because this is a perfect example of why it's needed.
