### ISSUE TITLE
Idea for a new bullet point

### ISSUE THREAD

**Issue by rluvaton** [goldbergyoni/nodebestpractices#945]
I don't really know how to write it but the point is, if your function return a promise you should use `async` to prevent the need to handle 2 types of error:
1. Rejected promise
2. Thrown error.

Code example:
```typescript
// Bad
function addNewMember(newMember): Promise<Member> {
  // Throws if validation fails
  Joi.assert(newMember, memberSchema);
  
  return db.addMember(newMember);
}

// Because we pass invalid input It will **throw an error** and not return a **rejected promise**
// this way making the function inconsistent
addNewMember(invalidInput)
  .catch(console.error);

// Good
async function addNewMember(newMember): Promise<Member> {
  // Throws if validation fails
  Joi.assert(newMember, memberSchema);
  
  return await db.addMember(newMember);
}

// Because we pass invalid input It will return a **rejected promise** only
addNewMember(invalidInput)
  .catch(console.error);
```

Unless it conflicts with point [2.3 - Distinguish operational vs programmer errors](https://github.com/goldbergyoni/nodebestpractices#-23-distinguish-operational-vs-programmer-errors)

Hope I explained it well 😬

**Comment by goldbergyoni** [comment]
@rluvaton As always bring valuable discussion. Sorry for the late reply.

Trying to simplify, let me know if sounds simpler and I'm not missing some case: For consistency and simplicity, prefer await + try-catch. This will trap all kind of errors whether sync, async and also when the target function is not tagged as async. One exception: When in-need to execute a code without waiting for it to complete (no await), then your advice comes relevant: P.catch must be used and the target function must return a promise

p.s. After writing this, I'm not sure that I did any simplification 😞, at least we have a draft to discuss

**Comment by rluvaton** [comment]
@goldbergyoni Sound a little simpler but summarize a lot better
