### ISSUE TITLE
Expire JWT page refers to outdated / discontinued packages

### ISSUE THREAD

**Issue by ccontour** [goldbergyoni/nodebestpractices#955]
https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/security/expirejwt.md

The last update to express-jwt-blacklist is 5 years ago, and the linked github on npm leads to a 404

https://www.npmjs.com/package/express-jwt-blacklist

**Comment by goldbergyoni** [comment]
Indeed an issue. Good catch @ccontour 

Is there a better alternative out there? I plan to search soon but maybe you already did and have better ideas

**Comment by ccontour** [comment]
I am trying to integrate with NestJS for my project, so starting with their passport stuff would be a good start in my book

https://docs.nestjs.com/security/authentication

https://www.npmjs.com/package/passport-jwt

I haven't actually done the reading yet, but I'm hoping to find something that'll let me keep track of the tokens in Redis and expire them similar to the way the page currently describes

**Comment by josh-hemphill** [comment]
The top result from a google search, [a dev.to article](https://dev.to/chukwutosin_/how-to-invalidate-a-jwt-using-a-blacklist-28dl), provides an example just using Redis directly and storing the user - token pairs for comparison later with Redis' built-in expiry functionality.  It seems to be straight-forward enough that a library to abstract it seems a at least a little superfluous.

**Comment by goldbergyoni** [comment]
@josh-hemphill Thanks for these words of wisdom.

> It seems to be straight-forward enough that a library to abstract it seems a at least a little superfluous.

Highly resonates with me. Per your suggestion, I would add a plain-code example instead of a lib. Probably 4-5 loc.

@josh-hemphill @ccontour If you'd like to continue the momentum and add that, that could be great. I can also do it sometimes soon

**Comment by josh-hemphill** [comment]
Still weighing the options on #959 
Perhaps it should be changed to something more generic like provide for immediate credential invalidation if using session-less tokens. Since we may want to instead suggest refresh tokens over denylists, as refresh tokens are more scalable and have a lot of other upsides for a slight increase in complexity.
