### ISSUE TITLE
[Bullet Point Idea] Use map with async with caution

### ISSUE THREAD

**Issue by rluvaton** [goldbergyoni/nodebestpractices#960]
# Use `.map` with `async` functions with caution

## Scenario:
Let's say we have a health monitor application that monitors DBs, websites, you name it
We run the health check every 30 seconds for every target

```js
async function doHealthCheck(target) {
  await someFunctionsThatTakesTime()
}

function runHealthChecks(targets) {
  console.log('Starting a health check');

  await Promise.all(
    targets.map(target => doHealthCheck(target))
  );

  console.log('Health check completed');
}
```

The problem here is when running the `targets.map(target => doHealthCheck(target))` the `doHealthCheck` immediately start running which runs the function that takes time, so in case we have a very large array, this would be problematic as it would stuck the computer (need to change it from stuck the computer), 

The solution for this is to use a Promise pool (unfortunately it doesn't have support natively)  [What is the best way to limit concurrency when using es6s promise all](https://stackoverflow.com/questions/40639432/what-is-the-best-way-to-limit-concurrency-when-using-es6s-promise-all)

of course, there are some cases you do want run all of them at the same time (please help me with examples as I don't have one in mind)

**Comment by goldbergyoni** [comment]
Do you refer to running too many things concurrently (not related to map necessarily) or are you concerned specifically with map? I assume you refer to the 1st option. Typically, our advice should be relevant to a big enough portion of developers, are there really many developers who will try running 1M functions concurrently?

**Comment by rluvaton** [comment]
> Do you refer to running too many things concurrently (not related to map necessarily) or are you concerned specifically with map? I assume you refer to the 1st option.

The 1st option.

> Typically, our advice should be relevant to a big enough portion of developers, are there really many developers who will try running 1M functions concurrently?

I don't think it's 1M functions concurrently, I remember when I did an internal NPM utility for my team that doing some tar and 
Untar for unknown number of files I needed to use that.

So I think what I'm trying to say is that sometimes, we need to do some operation for unknown number of _entities_ and then it's something we need to keep in mind

**Comment by rluvaton** [comment]
@elektronik2k5 what do you think?

**Comment by elektronik2k5** [comment]
I think that it is worth warning against this pattern and not suggest any specific recommendations, because the scenarios where this sort of mistake may be made can differ significantly. We can suggest a few approaches and have the reader decide which one matches their case best.
I also think that there has to be an eslint rule forbidding this pattern and perhaps its docs suggest alternatives.

**Comment by josh-hemphill** [comment]
Looking at this made me think that maybe now with the new `Promise.race()` it's become approachable to implement queuing (or I guess as mentioned this would be considered pooling) of promises without a library. e.g.:
```js
async function runHealthChecks (targets, queueSize) {
	console.log('Starting a health check');

	// Maps are most preferment for heavy set/delete operations
	const promiseQueue = new Map();

	/*	I thought it would be easier,
		but you do run into the issue that the promise returned
		by `Promise.race()` is not the same promise instance of
		the resolved promise, so you can't just stick it in a `Set()`
		and check `p1 === p2` so we have to create unique keys
		(could also be done with array indexes, but I prefer Map) */
	const addItem = (target) => {
		const _id = Symbol();
		promiseQueue.set(_id,doHealthCheck(target)
			.then((v) => ({_id,value:v})));
	};

	let targetIndex = Math.min(targets.length,queueSize);

	// Initializes queue and immediately starts them
	for (let i = 0;i<targetIndex;i++) {
		addItem(targets[i]);
	}
	/* `promiseQueue.size` gets checked on every iteration, so 
		we can grow it during iteration */
	for (let i = 0;i<promiseQueue.size;i++) {
		// Returns on the first promise to resolve or reject
		const {_id,value} = await Promise.race(promiseQueue.values());
		promiseQueue.delete(_id);
		console.log('CompletedVal: ' + value);

		/* Replace the completed one to maintain the queue size
			until we run out of targets */
		if (targetIndex < targets.length) {
			targetIndex++;
			addItem(targets[targetIndex]);
		}
	}

	console.log('Health checks completed');
}
```

**Comment by goldbergyoni** [comment]
@elektronik2k5 

> I also think that there has to be an eslint rule forbidding this pattern and perhaps its docs suggest alternatives.

Is this indeed an anti-pattern regardless of the map size? What if I put into a map a small array - Why is this a bad pattern?

@rluvaton @josh-hemphill Other thought - Should we (ever) set limits with code or shall we write eager code and let the infra do the scaling? In other words, when defining a batch of Y promises, we might starve the machine which can handle 5Y concurrently. Another approach would be to run as much as possible, then let the infra scale-out when RAM/network are too saturated. This will work better when there is a relatively stable throughput and compensatable tasks

**Comment by josh-hemphill** [comment]
I'm not sure. Thinking to the `mssql` database driver library, they have the developer manually set pool sizes; it might be for scenarios where you want to have multiple pools and make sure one receives priority by setting limits on others.

**Comment by rmortes** [comment]
@josh-hemphill If "`promisePool.size` gets checked every iteration", wouldn't it be better to wrap the await in a while loop?

```js
while (!promisePool.size) {
    const {_id,value} = await Promise.race(promisePool.values());
    promisePool.delete(_id);
    console.log('CompletedVal: ' + value);
}
```

**Comment by josh-hemphill** [comment]
> If "`promisePool.size` gets checked every iteration", wouldn't it be better to wrap the await in a while loop?
> 

I suppose you might also be able to do something like
```js
for (;!!promisePool.size;) {}
```
I always avoid using `while` with promises since last I heard it can block the event loop, blocking all other operations.

**Comment by rluvaton** [comment]
@josh-hemphill

> I suppose you might also be able to do something like
> ```js
> for (;!!promisePool.size;) {}
> ```

The problem in that is that it's not straight forward, and we always should aim to write simple code (if it's necessary, than IMO a comment is required)

> I always avoid using `while` with promises since last I heard it can block the event loop, blocking all other operations.


Could you give some reference to support your statement? 😀 

-----

**Comment by josh-hemphill** [comment]
> Could you give some reference to support your statement? 😀
Sure thing:

- https://stackoverflow.com/questions/34824460/why-does-a-while-loop-block-the-event-loop
- https://medium.com/@maxdignan/making-blocking-functions-non-blocking-in-javascript-dfeb9501301c

**Comment by rluvaton** [comment]
> > Could you give some reference to support your statement? 😀
> 
> 
> 
> Sure thing:
> 
> 
> 
> - https://stackoverflow.com/questions/34824460/why-does-a-while-loop-block-the-event-loop
> 
> - https://medium.com/@maxdignan/making-blocking-functions-non-blocking-in-javascript-dfeb9501301c
> 
> 
> 
> The reason I know this all to well is that I've tried using `while` with `Promise` to shim top-level await before it got introduced as a feature of Node and browsers. No matter what you do, no external promise can get resolved while your while loop is running, so putting your promise in the check for the loop just runs indefinitely. :( It was a sad realization after a week of work on it.

The condition in the loop is the same, whether it's a `for` or a `while` loop they act the same...

And from what I understand, and according to [this article](https://snyk.io/blog/nodejs-how-even-quick-async-functions-can-block-the-event-loop-starve-io/), other requests don't get handled because the next tick queue (registered via `nextTick()`), Other Micro Tasks (e.g Promises) queue need to be exhausted before moving from one phase to the other.

@elektronik2k5 WDYT?

**Comment by josh-hemphill** [comment]
> The condition in the loop is the same, whether it's a `for` or a `while` loop they act the same...

The condition in the loop doesn't matter at all. Here's an example of what I mean (using [this example](https://ourcodeworld.com/articles/read/317/how-to-check-if-a-javascript-promise-has-been-fulfilled-rejected-or-resolved) to make a queriable promise):

```js
let x = MakeQuerablePromise(fetch('https://www.google.com'))
while (true) {
  if (x.isFulfilled()) break;
}
console.log('this never executes because all promises are blocked')
```

**Comment by rluvaton** [comment]
> The condition in the loop doesn't matter at all. Here's an example of what I mean (using [this example](https://ourcodeworld.com/articles/read/317/how-to-check-if-a-javascript-promise-has-been-fulfilled-rejected-or-resolved) to make a queriable promise):
> 
> 
> 
> ```js
> 
> let x = MakeQuerablePromise(fetch('https://www.google.com'))
> 
> while (true) {
> 
>   if (x.isFulfilled()) break;
> 
> }
> 
> console.log('this never logs because all promises are blocked within the while loop')
> 
> ```

On that case you're right but doing `for(;true;)` have the same effect as your `while(true)`.
