### ISSUE TITLE
Welcome rluvaton as a new member in the maintainers team

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#969]
@rluvaton is doing magical PRs over the past weeks and we are proud to promote him to be an official maintainer ✨💜

CONTRIBUTING.md is located underneath ~root/.operations

**Comment by rluvaton** [comment]
I'm proud to be part of the team

**Comment by goldbergyoni** [comment]
@rluvaton Would you add your name + title to the 'Collaborators' section + PR? We typically move collaborators to the steering committee after few months

**Comment by rluvaton** [comment]
> @rluvaton Would you add your name + title to the 'Collaborators' section + PR?

Will do, just thinking how to create the blue circle around my profile picture 🤔 

> We typically move collaborators to the steering committee after few months

Looking forward for it!
