### ISSUE TITLE
Adding a comparison for web framework

### ISSUE THREAD

**Issue by rluvaton** [goldbergyoni/nodebestpractices#984]
As discussed with @goldbergyoni, we thought we need to add a deep comparison of web framework and the possible effect of choosing the framework later on in the development.

If you have another framework we need to compare or add another comparison criteria please add a comment

## Frameworks:
- Express
- Koa 
- Restify
- Fastify
- Nest.JS

## Comparison criteria:
- Usage (Downloads) - inflect on community help
- Release dates
- Ecosystem
- Support

**Comment by goldbergyoni** [comment]
Thanks for pushing @rluvaton 💪

Thoughts - This is important as it is one of the key core decision one should take when starting a new Node.js project

Focus on what matters - This comparison should cut through the clutter and highlight what is important:

a. First section should be an 'Executive summary' with the top ~5 dimensions
b. Only top 4 frameworks going by GH stars
c. Focus on facts and numbers

Dimension/Comparision sections - Executive summary, popularity, performance, functionality (features drill-down), maintainability, others?

Dimensions for example- Last year releases, OOTB authentication, OOTB OpenAPI, OOTB correlation id, OOTB many other features that every framework need, TypeScript and JS examples, many others - at least 50

Aesthetic - It should look beautiful and clean. I wish @idori could take care for this 🙏

cc @BrunoScheufler @sagirk @js-kyle @elektronik2k5 @kevynb @josh-hemphill
