### ISSUE TITLE
Create honor wall 🥇

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#995]
We should differentiate people who contribute once some small improvement (great and important!) from others who submitted an exceptional contribution like language translation or a new BP. Right now everybody are credited in the same way - Single list of contributors. 

I propose to create a dedicated section 'Honor Wall' with a bold image and name for those who:

1. Submitted a new best practices successfully (usually a long process)
2. Translated a language
3. Contributed more than 10 times

This list will get updated manually to honor those who have really made the great.

Thoughts?

**Comment by rluvaton** [comment]
I think it's a great idea!

**Comment by elektronik2k5** [comment]
I agree and think that instead of making an even bigger section compared to the already big contributors section, we should  convert the existing one to a list without images and the new section to look like the current one.

**Comment by goldbergyoni** [comment]
@elektronik2k5 Wouldn't we then kinda downgrade those who already contributed? Does the average reader really care how long is this section?
