### ISSUE TITLE
Add Josh as collaborator

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/nodebestpractices#997]
@josh-hemphill  Thanks for greatly being involved recently. It comes naturally to propose being official collaborators

What is the added value - Recognition. Being able to merge PRs.

What is needed - 5min a week or more.

If this is indeed interesting, just LMK and I'll take care of the details?

**Comment by josh-hemphill** [comment]
It sounds good. I should probably try and finish that PR I've had open for a month now. 😜

**Comment by goldbergyoni** [comment]
@josh-hemphill Happy to collaborate with you. Do only things that you feel passionate about now at this very moment.

**Comment by goldbergyoni** [comment]
@josh-hemphill Don't forget to PR your name to the collaborators section
